// Chengyu (成语) — Four-character idioms (Part 2)
// Chinesische Vier-Zeichen-Redewendungen fuer deutschsprachige Lernende — Erweiterung
// UI-Sprache: Deutsch

(function () {
  if (!window.CHENGYU_DATA) window.CHENGYU_DATA = [];
  window.CHENGYU_DATA = window.CHENGYU_DATA.concat([

    // ========================
    // === LEBENSWEISHEIT ===
    // ========================

    { word: '顺其自然', pinyin: 'shùn qí zì rán', meaning: 'den Dingen ihren natuerlichen Lauf lassen', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '有些事情强求不来，还是顺其自然吧。', pinyin: 'Yǒuxiē shìqíng qiángqiú bù lái, háishi shùn qí zì rán ba.', german: 'Manche Dinge kann man nicht erzwingen, lass es einfach seinen Lauf nehmen.' }] },
    { word: '知己知彼', pinyin: 'zhī jǐ zhī bǐ', meaning: 'sich selbst und den Gegner kennen; gute Vorbereitung', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '知己知彼，百战不殆。', pinyin: 'Zhī jǐ zhī bǐ, bǎi zhàn bù dài.', german: 'Wer sich selbst und den Gegner kennt, wird in hundert Schlachten nicht in Gefahr geraten.' }] },
    { word: '物以类聚', pinyin: 'wù yǐ lèi jù', meaning: 'Gleich und Gleich gesellt sich gern', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '物以类聚，人以群分。', pinyin: 'Wù yǐ lèi jù, rén yǐ qún fēn.', german: 'Gleich und Gleich gesellt sich gern — Menschen finden zueinander, die aehnlich sind.' }] },
    { word: '海阔天空', pinyin: 'hǎi kuò tiān kōng', meaning: 'weites Meer und offener Himmel; grenzenlos und frei', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '退一步海阔天空。', pinyin: 'Tuì yī bù hǎi kuò tiān kōng.', german: 'Einen Schritt zuruecktreten und die Welt wird weit und offen.' }] },
    { word: '吃苦耐劳', pinyin: 'chī kǔ nài láo', meaning: 'Muehen und Strapazen ertragen koennen; hart im Nehmen', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '他从小吃苦耐劳，什么困难都不怕。', pinyin: 'Tā cóng xiǎo chī kǔ nài láo, shénme kùnnán dōu bù pà.', german: 'Er hat von Kindheit an gelernt, Muehen zu ertragen, und fuerchtet keine Schwierigkeiten.' }] },
    { word: '心灵手巧', pinyin: 'xīn líng shǒu qiǎo', meaning: 'geschickter Geist und geschickte Haende; handwerklich begabt', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '她心灵手巧，什么手工活都会做。', pinyin: 'Tā xīn líng shǒu qiǎo, shénme shǒugōng huó dōu huì zuò.', german: 'Sie ist handwerklich sehr begabt und kann jede Handarbeit ausfuehren.' }] },
    { word: '兼听则明', pinyin: 'jiān tīng zé míng', meaning: 'wer beide Seiten hoert, urteilt weise', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '做领导要兼听则明，偏听则暗。', pinyin: 'Zuò lǐngdǎo yào jiān tīng zé míng, piān tīng zé àn.', german: 'Als Fuehrungskraft muss man beide Seiten hoeren, um weise zu urteilen.' }] },
    { word: '百年树人', pinyin: 'bǎi nián shù rén', meaning: 'hundert Jahre, um Menschen heranzubilden; Bildung braucht Geduld', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '十年树木，百年树人，教育是长远的事业。', pinyin: 'Shí nián shù mù, bǎi nián shù rén, jiàoyù shì chángyuǎn de shìyè.', german: 'Zehn Jahre, um einen Baum zu ziehen, hundert Jahre, um Menschen heranzubilden — Bildung ist ein langfristiges Unterfangen.' }] },
    { word: '一言难尽', pinyin: 'yī yán nán jìn', meaning: 'mit einem Wort nicht zu erklaeren; eine lange Geschichte', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '这件事情一言难尽，说来话长。', pinyin: 'Zhè jiàn shìqíng yī yán nán jìn, shuō lái huà cháng.', german: 'Diese Angelegenheit ist mit einem Wort nicht zu erklaeren, es ist eine lange Geschichte.' }] },
    { word: '审时度势', pinyin: 'shěn shí duó shì', meaning: 'die Lage sorgfaeltig einschaetzen; die Zeichen der Zeit lesen', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '成功的领导者善于审时度势。', pinyin: 'Chénggōng de lǐngdǎozhě shànyú shěn shí duó shì.', german: 'Erfolgreiche Fuehrungskraefte verstehen es, die Lage sorgfaeltig einzuschaetzen.' }] },
    { word: '饮水思源', pinyin: 'yǐn shuǐ sī yuán', meaning: 'beim Trinken an die Quelle denken; dankbar sein', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '我们要饮水思源，不忘帮助过我们的人。', pinyin: 'Wǒmen yào yǐn shuǐ sī yuán, bù wàng bāngzhù guò wǒmen de rén.', german: 'Wir sollen dankbar sein und die Menschen nicht vergessen, die uns geholfen haben.' }] },
    { word: '实至名归', pinyin: 'shí zhì míng guī', meaning: 'verdiente Anerkennung; der Erfolg kommt zu dem, der es verdient', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '他获得这个奖项是实至名归。', pinyin: 'Tā huòdé zhège jiǎngxiàng shì shí zhì míng guī.', german: 'Dass er diesen Preis gewonnen hat, ist eine verdiente Anerkennung.' }] },
    { word: '居高临下', pinyin: 'jū gāo lín xià', meaning: 'von oben herab; eine ueberlegene Position einnehmen', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '跟人说话不要居高临下，要平等对待。', pinyin: 'Gēn rén shuōhuà bù yào jū gāo lín xià, yào píngděng duìdài.', german: 'Sprich nicht von oben herab mit Leuten, behandle sie auf Augenhoehe.' }] },
    { word: '百感交集', pinyin: 'bǎi gǎn jiāo jí', meaning: 'hundert Gefuehle durcheinander; von Emotionen uebermannt', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '毕业典礼上，他百感交集。', pinyin: 'Bìyè diǎnlǐ shàng, tā bǎi gǎn jiāo jí.', german: 'Bei der Abschlussfeier wurde er von gemischten Gefuehlen uebermannt.' }] },

    // ========================
    // === CHARAKTER ===
    // ========================

    { word: '刚正不阿', pinyin: 'gāng zhèng bù ē', meaning: 'aufrecht und unbeugsam; integer', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他为人刚正不阿，从不向权势低头。', pinyin: 'Tā wéirén gāng zhèng bù ē, cóng bù xiàng quánshì dītóu.', german: 'Er ist aufrecht und integer und beugt sich niemals der Macht.' }] },
    { word: '虚怀若谷', pinyin: 'xū huái ruò gǔ', meaning: 'bescheiden wie ein leeres Tal; aufgeschlossen und demuetig', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '真正的大师虚怀若谷，从不炫耀。', pinyin: 'Zhēnzhèng de dàshī xū huái ruò gǔ, cóng bù xuànyào.', german: 'Wahre Meister sind demuetig wie ein leeres Tal und prahlen nie.' }] },
    { word: '见利忘义', pinyin: 'jiàn lì wàng yì', meaning: 'beim Anblick von Gewinn die Gerechtigkeit vergessen; geldgierig', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '不要做见利忘义的人。', pinyin: 'Bù yào zuò jiàn lì wàng yì de rén.', german: 'Sei kein Mensch, der fuer Geld seine Prinzipien verraet.' }] },
    { word: '德高望重', pinyin: 'dé gāo wàng zhòng', meaning: 'von hoher Tugend und grossem Ansehen; hoch angesehen', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他是村里德高望重的长辈。', pinyin: 'Tā shì cūn lǐ dé gāo wàng zhòng de zhǎngbèi.', german: 'Er ist ein hoch angesehener Aeltester im Dorf.' }] },
    { word: '口是心非', pinyin: 'kǒu shì xīn fēi', meaning: 'der Mund sagt ja, das Herz meint nein; heuchlerisch', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '她总是口是心非，说一套做一套。', pinyin: 'Tā zǒng shì kǒu shì xīn fēi, shuō yī tào zuò yī tào.', german: 'Sie ist immer heuchlerisch, sagt das eine und tut das andere.' }] },
    { word: '厚颜无耻', pinyin: 'hòu yán wú chǐ', meaning: 'dickhaeuetig und schamlos; unverschaemt', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他厚颜无耻地把别人的功劳据为己有。', pinyin: 'Tā hòu yán wú chǐ de bǎ biéren de gōngláo jù wéi jǐ yǒu.', german: 'Er hat schamlos die Verdienste anderer fuer sich beansprucht.' }] },
    { word: '忍辱负重', pinyin: 'rěn rǔ fù zhòng', meaning: 'Schmach ertragen und schwere Last tragen; grosse Geduld zeigen', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他忍辱负重多年，终于证明了自己的清白。', pinyin: 'Tā rěn rǔ fù zhòng duō nián, zhōngyú zhèngmíng le zìjǐ de qīngbái.', german: 'Er ertrug jahrelang Ungerechtigkeit und bewies schliesslich seine Unschuld.' }] },
    { word: '平易近人', pinyin: 'píng yì jìn rén', meaning: 'freundlich und zugaenglich; nahbar', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '虽然他是大老板，但为人平易近人。', pinyin: 'Suīrán tā shì dà lǎobǎn, dàn wéirén píng yì jìn rén.', german: 'Obwohl er ein grosser Chef ist, ist er sehr zugaenglich und nahbar.' }] },
    { word: '胆大心细', pinyin: 'dǎn dà xīn xì', meaning: 'mutig und doch umsichtig; kuehn aber sorgfaeltig', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '做这项工作需要胆大心细。', pinyin: 'Zuò zhè xiàng gōngzuò xūyào dǎn dà xīn xì.', german: 'Fuer diese Arbeit braucht man Mut und Sorgfalt zugleich.' }] },
    { word: '助人为乐', pinyin: 'zhù rén wéi lè', meaning: 'anderen zu helfen als Freude betrachten; hilfsbereit', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '她总是助人为乐，大家都喜欢她。', pinyin: 'Tā zǒng shì zhù rén wéi lè, dàjiā dōu xǐhuan tā.', german: 'Sie hilft immer gerne anderen, deshalb moegen sie alle.' }] },
    { word: '心胸开阔', pinyin: 'xīn xiōng kāi kuò', meaning: 'ein weites Herz haben; grosszuegig und aufgeschlossen', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '心胸开阔的人不会为小事生气。', pinyin: 'Xīn xiōng kāi kuò de rén bù huì wèi xiǎo shì shēngqì.', german: 'Menschen mit einem weiten Herzen aergern sich nicht ueber Kleinigkeiten.' }] },
    { word: '恃强凌弱', pinyin: 'shì qiáng líng ruò', meaning: 'die eigene Staerke ausnutzen, um Schwaechere zu schikanieren', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '我们不能恃强凌弱，要公平对待每个人。', pinyin: 'Wǒmen bù néng shì qiáng líng ruò, yào gōngpíng duìdài měi gè rén.', german: 'Wir duerfen nicht Schwaechere schikanieren, sondern muessen jeden fair behandeln.' }] },
    { word: '临危不惧', pinyin: 'lín wēi bù jù', meaning: 'angesichts von Gefahr keine Furcht zeigen; unerschrocken', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '消防员临危不惧，冲进了火场。', pinyin: 'Xiāofángyuán lín wēi bù jù, chōng jìn le huǒchǎng.', german: 'Der Feuerwehrmann zeigte keine Furcht vor der Gefahr und stuermte in das Feuer.' }] },

    // ========================
    // === NATUR ===
    // ========================

    { word: '春意盎然', pinyin: 'chūn yì àng rán', meaning: 'voller Fruehlingsatmosphaere; der Fruehling liegt in der Luft', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '公园里春意盎然，到处都是花。', pinyin: 'Gōngyuán lǐ chūn yì àng rán, dàochù dōu shì huā.', german: 'Im Park liegt der Fruehling in der Luft, ueberall bluehen Blumen.' }] },
    { word: '风调雨顺', pinyin: 'fēng tiáo yǔ shùn', meaning: 'Wind und Regen zur rechten Zeit; guenstiges Klima', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '今年风调雨顺，农民收成很好。', pinyin: 'Jīnnián fēng tiáo yǔ shùn, nóngmín shōuchéng hěn hǎo.', german: 'Dieses Jahr war das Klima guenstig und die Bauern hatten eine gute Ernte.' }] },
    { word: '秋高气爽', pinyin: 'qiū gāo qì shuǎng', meaning: 'hoher Herbsthimmel und frische Luft; schoenes Herbstwetter', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '秋高气爽的日子最适合出去爬山。', pinyin: 'Qiū gāo qì shuǎng de rìzi zuì shìhé chūqù páshān.', german: 'An schoenen Herbsttagen eignet es sich am besten zum Bergwandern.' }] },
    { word: '碧水蓝天', pinyin: 'bì shuǐ lán tiān', meaning: 'smaragdgruenes Wasser und blauer Himmel; makellose Natur', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '我们要保护碧水蓝天的美好环境。', pinyin: 'Wǒmen yào bǎohù bì shuǐ lán tiān de měihǎo huánjìng.', german: 'Wir muessen die wunderschoene Umwelt mit klarem Wasser und blauem Himmel schuetzen.' }] },
    { word: '风花雪月', pinyin: 'fēng huā xuě yuè', meaning: 'Wind, Blumen, Schnee und Mond; romantische Landschaften oder Liebeleien', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '他喜欢写风花雪月的诗歌。', pinyin: 'Tā xǐhuan xiě fēng huā xuě yuè de shīgē.', german: 'Er schreibt gerne romantische Gedichte ueber Natur und Liebe.' }] },
    { word: '电闪雷鸣', pinyin: 'diàn shǎn léi míng', meaning: 'Blitz und Donner; ein heftiges Gewitter', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '外面电闪雷鸣，大雨倾盆。', pinyin: 'Wàimiàn diàn shǎn léi míng, dàyǔ qīngpén.', german: 'Draussen blitzt und donnert es, der Regen giesst in Stroemen.' }] },
    { word: '白雪皑皑', pinyin: 'bái xuě ái ái', meaning: 'strahlend weisser Schnee; schneebedeckt', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '冬天的阿尔卑斯山白雪皑皑，非常壮观。', pinyin: 'Dōngtiān de Ā\'ěrbēisī shān bái xuě ái ái, fēicháng zhuàngguān.', german: 'Die Alpen sind im Winter schneebedeckt, es ist sehr beeindruckend.' }] },
    { word: '绿树成荫', pinyin: 'lǜ shù chéng yīn', meaning: 'gruene Baeume spenden Schatten; dichte gruene Vegetation', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '这条街道绿树成荫，非常凉爽。', pinyin: 'Zhè tiáo jiēdào lǜ shù chéng yīn, fēicháng liángshuǎng.', german: 'Diese Strasse ist von gruen belaubten Baeumen beschattet und sehr angenehm kuehl.' }] },
    { word: '落叶归根', pinyin: 'luò yè guī gēn', meaning: 'fallende Blaetter kehren zu den Wurzeln zurueck; Heimkehr', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '他在国外生活了三十年，最终还是落叶归根，回到了家乡。', pinyin: 'Tā zài guówài shēnghuó le sānshí nián, zuìzhōng háishi luò yè guī gēn, huí dào le jiāxiāng.', german: 'Er lebte dreissig Jahre im Ausland, kehrte aber schliesslich doch in seine Heimat zurueck.' }] },
    { word: '晴空万里', pinyin: 'qíng kōng wàn lǐ', meaning: 'klarer Himmel auf zehntausend Meilen; wolkenloser Himmel', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '今天晴空万里，是个出游的好日子。', pinyin: 'Jīntiān qíng kōng wàn lǐ, shì gè chūyóu de hǎo rìzi.', german: 'Heute ist der Himmel wolkenlos, ein perfekter Tag fuer einen Ausflug.' }] },
    { word: '波涛汹涌', pinyin: 'bō tāo xiōng yǒng', meaning: 'Wellen tuermen sich auf; stuermische See', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '大海波涛汹涌，渔船不敢出海。', pinyin: 'Dàhǎi bō tāo xiōng yǒng, yúchuán bù gǎn chūhǎi.', german: 'Das Meer ist stuermisch, die Fischerboote wagen sich nicht hinaus.' }] },
    { word: '烟消云散', pinyin: 'yān xiāo yún sàn', meaning: 'Rauch verfliegt und Wolken zerstreuen sich; voellig verschwinden', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '误会解开后，所有的不愉快都烟消云散了。', pinyin: 'Wùhuì jiě kāi hòu, suǒyǒu de bù yúkuài dōu yān xiāo yún sàn le.', german: 'Nachdem das Missverstaendnis geklaert war, loeste sich aller Aerger in Luft auf.' }] },

    // ========================
    // === ERFOLG ===
    // ========================

    { word: '百战百胜', pinyin: 'bǎi zhàn bǎi shèng', meaning: 'hundert Schlachten, hundert Siege; unbesiegbar', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '他在辩论比赛中百战百胜。', pinyin: 'Tā zài biànlùn bǐsài zhōng bǎi zhàn bǎi shèng.', german: 'Er ist in Debattenwettbewerben ungeschlagen.' }] },
    { word: '出类拔萃', pinyin: 'chū lèi bá cuì', meaning: 'aus der Masse herausragen; hervorragend', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '她的表现出类拔萃，获得了最高奖。', pinyin: 'Tā de biǎoxiàn chū lèi bá cuì, huòdé le zuìgāo jiǎng.', german: 'Ihre Leistung war herausragend und sie erhielt den hoechsten Preis.' }] },
    { word: '马不停蹄', pinyin: 'mǎ bù tíng tí', meaning: 'das Pferd haelt nicht an; ohne Pause weiterarbeiten', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '为了赶工期，工人们马不停蹄地工作。', pinyin: 'Wèile gǎn gōngqī, gōngrénmen mǎ bù tíng tí de gōngzuò.', german: 'Um die Frist einzuhalten, arbeiten die Arbeiter ohne Pause.' }] },
    { word: '崭露头角', pinyin: 'zhǎn lù tóu jiǎo', meaning: 'zum ersten Mal sein Talent zeigen; sich einen Namen machen', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '这位年轻画家在国际比赛中崭露头角。', pinyin: 'Zhè wèi niánqīng huàjiā zài guójì bǐsài zhōng zhǎn lù tóu jiǎo.', german: 'Dieser junge Maler hat sich bei einem internationalen Wettbewerb erstmals einen Namen gemacht.' }] },
    { word: '步步高升', pinyin: 'bù bù gāo shēng', meaning: 'Schritt fuer Schritt aufsteigen; stetige Befoerderung', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '祝你新年步步高升！', pinyin: 'Zhù nǐ xīnnián bù bù gāo shēng!', german: 'Ich wuensche dir im neuen Jahr stetigen Aufstieg!' }] },
    { word: '一路顺风', pinyin: 'yī lù shùn fēng', meaning: 'den ganzen Weg mit Rueckenwind; gute Reise', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '朋友要出国了，我祝他一路顺风。', pinyin: 'Péngyou yào chūguó le, wǒ zhù tā yī lù shùn fēng.', german: 'Mein Freund verreist ins Ausland, ich wuensche ihm eine gute Reise.' }] },
    { word: '名扬四海', pinyin: 'míng yáng sì hǎi', meaning: 'der Ruf verbreitet sich ueber vier Meere; weltbekannt', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '这个品牌已经名扬四海。', pinyin: 'Zhège pǐnpái yǐjīng míng yáng sì hǎi.', german: 'Diese Marke ist bereits weltbekannt.' }] },
    { word: '所向披靡', pinyin: 'suǒ xiàng pī mǐ', meaning: 'ueberall, wo man hingeht, alles niederreissen; unaufhaltsam', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '这支球队所向披靡，连赢十场。', pinyin: 'Zhè zhī qiúduì suǒ xiàng pī mǐ, lián yíng shí chǎng.', german: 'Dieses Team ist unaufhaltsam und hat zehn Spiele hintereinander gewonnen.' }] },
    { word: '一鼓作气', pinyin: 'yī gǔ zuò qì', meaning: 'beim ersten Trommelschlag den Mut fassen; in einem Zug erledigen', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '我们要一鼓作气，把这个任务完成。', pinyin: 'Wǒmen yào yī gǔ zuò qì, bǎ zhège rènwù wánchéng.', german: 'Wir muessen in einem Zug diese Aufgabe erledigen.' }] },
    { word: '力挽狂澜', pinyin: 'lì wǎn kuáng lán', meaning: 'die wilden Wellen mit Kraft zurueckhalten; eine Krise abwenden', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '关键时刻，他力挽狂澜，拯救了公司。', pinyin: 'Guānjiàn shíkè, tā lì wǎn kuáng lán, zhěngjiù le gōngsī.', german: 'Im entscheidenden Moment wendete er die Krise ab und rettete das Unternehmen.' }] },
    { word: '登峰造极', pinyin: 'dēng fēng zào jí', meaning: 'den Gipfel erklimmen; den Hoehepunkt erreichen', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '她的演技已经登峰造极。', pinyin: 'Tā de yǎnjì yǐjīng dēng fēng zào jí.', german: 'Ihre Schauspielkunst hat den absoluten Hoehepunkt erreicht.' }] },
    { word: '遥遥领先', pinyin: 'yáo yáo lǐng xiān', meaning: 'mit grossem Abstand fuehren; weit voraus sein', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '这家公司在技术创新方面遥遥领先。', pinyin: 'Zhè jiā gōngsī zài jìshù chuàngxīn fāngmiàn yáo yáo lǐng xiān.', german: 'Dieses Unternehmen ist im Bereich technologischer Innovation weit voraus.' }] },

    // ========================
    // === GEFUEHLE ===
    // ========================

    { word: '喜极而泣', pinyin: 'xǐ jí ér qì', meaning: 'vor Freude weinen; Freudentraenen vergiessen', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '得知考上大学的消息，她喜极而泣。', pinyin: 'Dé zhī kǎo shàng dàxué de xiāoxi, tā xǐ jí ér qì.', german: 'Als sie erfuhr, dass sie an der Uni angenommen wurde, weinte sie vor Freude.' }] },
    { word: '怒发冲冠', pinyin: 'nù fà chōng guān', meaning: 'vor Wut stehen die Haare zu Berge; rasend vor Zorn', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '听到这个不公平的判决，他怒发冲冠。', pinyin: 'Tīngdào zhège bù gōngpíng de pànjué, tā nù fà chōng guān.', german: 'Als er das ungerechte Urteil hoerte, war er rasend vor Zorn.' }] },
    { word: '归心似箭', pinyin: 'guī xīn sì jiàn', meaning: 'das Herz fliegt wie ein Pfeil nach Hause; sehnsuechtiges Heimweh', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '在外漂泊多年，他归心似箭。', pinyin: 'Zài wài piāobó duō nián, tā guī xīn sì jiàn.', german: 'Nach vielen Jahren in der Fremde sehnt er sich brennend nach Hause.' }] },
    { word: '如坐针毡', pinyin: 'rú zuò zhēn zhān', meaning: 'wie auf Nadeln sitzen; sich sehr unwohl fuehlen', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '等待面试结果时，他如坐针毡。', pinyin: 'Děngdài miànshì jiéguǒ shí, tā rú zuò zhēn zhān.', german: 'Waehrend er auf das Ergebnis des Vorstellungsgespraechs wartete, sass er wie auf Nadeln.' }] },
    { word: '乐极生悲', pinyin: 'lè jí shēng bēi', meaning: 'wenn die Freude den Hoehepunkt erreicht, entsteht Trauer; nach uebermassiger Freude kommt Leid', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '庆祝过度导致意外，真是乐极生悲。', pinyin: 'Qìngzhù guòdù dǎozhì yìwài, zhēn shì lè jí shēng bēi.', german: 'Uebertriebenes Feiern fuehrte zu einem Unfall — uebermassige Freude schlug in Leid um.' }] },
    { word: '黯然神伤', pinyin: 'àn rán shén shāng', meaning: 'vor Trauer niedergeschlagen; schwermuetig', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '听到老友去世的消息，他黯然神伤。', pinyin: 'Tīngdào lǎo yǒu qùshì de xiāoxi, tā àn rán shén shāng.', german: 'Als er vom Tod seines alten Freundes erfuhr, war er tief betruebbt.' }] },
    { word: '得意忘形', pinyin: 'dé yì wàng xíng', meaning: 'vor Freude den Anstand vergessen; uebermuetig werden', type: 'Chengyu', level: 'HSK5', category: 'Gefuehle', examples: [{ chinese: '别得意忘形，要保持谦虚。', pinyin: 'Bié dé yì wàng xíng, yào bǎochí qiānxū.', german: 'Werde nicht uebermuetig, bleib bescheiden.' }] },
    { word: '触景生情', pinyin: 'chù jǐng shēng qíng', meaning: 'beim Anblick einer Szene Gefuehle wecken; Erinnerungen hervorrufen', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '回到故乡，他触景生情，想起了童年。', pinyin: 'Huí dào gùxiāng, tā chù jǐng shēng qíng, xiǎng qǐ le tóngnián.', german: 'Zurueck in der Heimat weckte der Anblick Erinnerungen an seine Kindheit.' }] },
    { word: '心如刀割', pinyin: 'xīn rú dāo gē', meaning: 'das Herz fuehlt sich an wie von Messern geschnitten; herzzerreissend', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '看到孩子受苦，母亲心如刀割。', pinyin: 'Kàn dào háizi shòukǔ, mǔqīn xīn rú dāo gē.', german: 'Zu sehen, wie das Kind leidet, ist fuer die Mutter herzzerreissend.' }] },
    { word: '欣喜若狂', pinyin: 'xīn xǐ ruò kuáng', meaning: 'sich wahnsinnig freuen; vor Freude fast verrueckt werden', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '中奖的消息让他欣喜若狂。', pinyin: 'Zhòngjiǎng de xiāoxi ràng tā xīn xǐ ruò kuáng.', german: 'Die Nachricht vom Lottogewinn machte ihn wahnsinnig vor Freude.' }] },
    { word: '心旷神怡', pinyin: 'xīn kuàng shén yí', meaning: 'das Herz weitet sich und der Geist erfrischt sich; heiter und entspannt', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '站在山顶上，让人心旷神怡。', pinyin: 'Zhàn zài shān dǐng shàng, ràng rén xīn kuàng shén yí.', german: 'Auf dem Berggipfel zu stehen, erfrischt Herz und Geist.' }] },
    { word: '魂不守舍', pinyin: 'hún bù shǒu shě', meaning: 'die Seele verlaesst den Koerper; geistesabwesend', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '他最近魂不守舍的，好像有什么心事。', pinyin: 'Tā zuìjìn hún bù shǒu shě de, hǎoxiàng yǒu shénme xīnshì.', german: 'Er ist in letzter Zeit voellig geistesabwesend, als haette er etwas auf dem Herzen.' }] },
    { word: '悲愤交加', pinyin: 'bēi fèn jiāo jiā', meaning: 'Trauer und Wut vermischen sich; voller Kummer und Empoerung', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '听到这不公正的消息，他悲愤交加。', pinyin: 'Tīngdào zhè bù gōngzhèng de xiāoxi, tā bēi fèn jiāo jiā.', german: 'Als er die ungerechte Nachricht hoerte, war er voller Trauer und Empoerung.' }] },

    // ========================
    // === ARBEIT ===
    // ========================

    { word: '夜以继日', pinyin: 'yè yǐ jì rì', meaning: 'die Nacht an den Tag anreihen; Tag und Nacht arbeiten', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '他夜以继日地工作，终于完成了项目。', pinyin: 'Tā yè yǐ jì rì de gōngzuò, zhōngyú wánchéng le xiàngmù.', german: 'Er arbeitete Tag und Nacht und schloss schliesslich das Projekt ab.' }] },
    { word: '兢兢业业', pinyin: 'jīng jīng yè yè', meaning: 'gewissenhaft und sorgfaeltig arbeiten; pflichtbewusst', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '他兢兢业业地工作了三十年。', pinyin: 'Tā jīng jīng yè yè de gōngzuò le sānshí nián.', german: 'Er hat dreissig Jahre lang gewissenhaft gearbeitet.' }] },
    { word: '精打细算', pinyin: 'jīng dǎ xì suàn', meaning: 'genau rechnen und sparsam wirtschaften; sorgfaeltig kalkulieren', type: 'Chengyu', level: 'HSK5', category: 'Arbeit', examples: [{ chinese: '过日子要精打细算，不能大手大脚。', pinyin: 'Guò rìzi yào jīng dǎ xì suàn, bù néng dà shǒu dà jiǎo.', german: 'Im Alltag muss man sparsam wirtschaften und darf nicht verschwenderisch sein.' }] },
    { word: '任重道远', pinyin: 'rèn zhòng dào yuǎn', meaning: 'die Aufgabe ist schwer und der Weg ist lang; grosse Verantwortung', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '环境保护任重道远，需要每个人的努力。', pinyin: 'Huánjìng bǎohù rèn zhòng dào yuǎn, xūyào měi gè rén de nǔlì.', german: 'Der Umweltschutz ist eine grosse Aufgabe mit langem Weg, die den Einsatz jedes Einzelnen erfordert.' }] },
    { word: '不遗余力', pinyin: 'bù yí yú lì', meaning: 'keine Kraft uebrig lassen; alles geben', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '他不遗余力地推广环保理念。', pinyin: 'Tā bù yí yú lì de tuīguǎng huánbǎo lǐniàn.', german: 'Er setzt sich mit aller Kraft fuer den Umweltschutzgedanken ein.' }] },
    { word: '驾轻就熟', pinyin: 'jià qīng jiù shú', meaning: 'ein leichtes Fahrzeug auf vertrautem Weg lenken; Routine haben', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '这项工作他已经驾轻就熟了。', pinyin: 'Zhè xiàng gōngzuò tā yǐjīng jià qīng jiù shú le.', german: 'Diese Arbeit ist fuer ihn laengst Routine.' }] },
    { word: '集思广益', pinyin: 'jí sī guǎng yì', meaning: 'Ideen sammeln fuer groesseren Nutzen; gemeinsam brainstormen', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '我们开个会集思广益，看看怎么解决这个问题。', pinyin: 'Wǒmen kāi gè huì jí sī guǎng yì, kànkan zěnme jiějué zhège wèntí.', german: 'Lass uns eine Besprechung einberufen, um gemeinsam Ideen zu sammeln und das Problem zu loesen.' }] },
    { word: '埋头苦干', pinyin: 'mái tóu kǔ gàn', meaning: 'den Kopf senken und hart arbeiten; sich still in die Arbeit vertiefen', type: 'Chengyu', level: 'HSK5', category: 'Arbeit', examples: [{ chinese: '他总是埋头苦干，从不抱怨。', pinyin: 'Tā zǒng shì mái tóu kǔ gàn, cóng bù bàoyuàn.', german: 'Er vertieft sich still in seine Arbeit und beschwert sich nie.' }] },
    { word: '事必躬亲', pinyin: 'shì bì gōng qīn', meaning: 'alles persoenlich erledigen muessen; Mikromanagement', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '老板事必躬亲，员工反而没有发挥的空间。', pinyin: 'Lǎobǎn shì bì gōng qīn, yuángōng fǎn\'ér méiyǒu fāhuī de kōngjiān.', german: 'Der Chef macht alles selbst, sodass die Mitarbeiter keinen Spielraum haben.' }] },
    { word: '精雕细刻', pinyin: 'jīng diāo xì kè', meaning: 'fein schnitzen und sorgfaeltig meisseln; mit groesster Sorgfalt arbeiten', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '这件作品是他精雕细刻的成果。', pinyin: 'Zhè jiàn zuòpǐn shì tā jīng diāo xì kè de chéngguǒ.', german: 'Dieses Werk ist das Ergebnis seiner sorgfaeltigsten Arbeit.' }] },
    { word: '分秒必争', pinyin: 'fēn miǎo bì zhēng', meaning: 'um jede Minute und Sekunde kaempfen; keine Zeit verschwenden', type: 'Chengyu', level: 'HSK5', category: 'Arbeit', examples: [{ chinese: '救灾工作分秒必争，不能有任何延误。', pinyin: 'Jiùzāi gōngzuò fēn miǎo bì zhēng, bù néng yǒu rènhé yánwù.', german: 'Bei der Katastrophenhilfe zaehlt jede Sekunde, es darf keine Verzoegerung geben.' }] },
    { word: '大公无私', pinyin: 'dà gōng wú sī', meaning: 'oeffentliches Interesse ueber persoenliches stellen; selbstlos und gerecht', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '他处理问题大公无私，不偏向任何一方。', pinyin: 'Tā chǔlǐ wèntí dà gōng wú sī, bù piānxiàng rènhé yī fāng.', german: 'Er behandelt Probleme selbstlos und gerecht, ohne eine Seite zu bevorzugen.' }] },

    // ========================
    // === BEZIEHUNGEN ===
    // ========================

    { word: '白头偕老', pinyin: 'bái tóu xié lǎo', meaning: 'zusammen alt werden bis die Haare weiss sind; lebenslange Liebe', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '祝你们白头偕老，永远幸福！', pinyin: 'Zhù nǐmen bái tóu xié lǎo, yǒngyuǎn xìngfú!', german: 'Ich wuensche euch, zusammen alt zu werden und fuer immer gluecklich zu sein!' }] },
    { word: '肝胆相照', pinyin: 'gān dǎn xiāng zhào', meaning: 'einander Leber und Galle zeigen; voellige Offenheit und Treue', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们是肝胆相照的好兄弟。', pinyin: 'Tāmen shì gān dǎn xiāng zhào de hǎo xiōngdì.', german: 'Sie sind bruederliche Freunde in voelliger Offenheit und Treue.' }] },
    { word: '海誓山盟', pinyin: 'hǎi shì shān méng', meaning: 'Schwuere so bestaendig wie Meer und Berge; ewige Liebesschweise', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '年轻人的海誓山盟不一定能经得住时间的考验。', pinyin: 'Niánqīng rén de hǎi shì shān méng bù yīdìng néng jīng de zhù shíjiān de kǎoyàn.', german: 'Die ewigen Liebesschweise junger Menschen bestehen nicht immer die Pruefung der Zeit.' }] },
    { word: '形影相随', pinyin: 'xíng yǐng xiāng suí', meaning: 'Gestalt und Schatten folgen einander; unzertrennlich', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们从小就是形影相随的好朋友。', pinyin: 'Tāmen cóng xiǎo jiùshì xíng yǐng xiāng suí de hǎo péngyou.', german: 'Sie sind seit ihrer Kindheit unzertrennliche Freunde.' }] },
    { word: '萍水相逢', pinyin: 'píng shuǐ xiāng féng', meaning: 'sich wie Wasserlinsen zufaellig treffen; eine zufaellige Begegnung', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '我们只是萍水相逢，谈不上深交。', pinyin: 'Wǒmen zhǐshì píng shuǐ xiāng féng, tán bù shàng shēn jiāo.', german: 'Wir haben uns nur zufaellig getroffen, von einer tiefen Freundschaft kann keine Rede sein.' }] },
    { word: '恩重如山', pinyin: 'ēn zhòng rú shān', meaning: 'die Guete ist schwer wie ein Berg; tiefe Dankbarkeit', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '父母的恩情恩重如山。', pinyin: 'Fùmǔ de ēnqíng ēn zhòng rú shān.', german: 'Die Guete der Eltern wiegt so schwer wie ein Berg.' }] },
    { word: '情深意重', pinyin: 'qíng shēn yì zhòng', meaning: 'tiefe Gefuehle und aufrichtige Zuneigung', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他给她写了一封情深意重的信。', pinyin: 'Tā gěi tā xiě le yī fēng qíng shēn yì zhòng de xìn.', german: 'Er schrieb ihr einen Brief voller tiefer Gefuehle und aufrichtiger Zuneigung.' }] },
    { word: '举案齐眉', pinyin: 'jǔ àn qí méi', meaning: 'das Tablett bis zu den Augenbrauen heben; respektvolle Ehe', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们夫妻举案齐眉，感情很好。', pinyin: 'Tāmen fūqī jǔ àn qí méi, gǎnqíng hěn hǎo.', german: 'Das Ehepaar behandelt einander mit grossem Respekt und hat eine gute Beziehung.' }] },
    { word: '同舟共济', pinyin: 'tóng zhōu gòng jì', meaning: 'im selben Boot sitzen und gemeinsam uebersetzen; zusammenhalten in schwierigen Zeiten', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '在困难面前，我们要同舟共济。', pinyin: 'Zài kùnnán miànqián, wǒmen yào tóng zhōu gòng jì.', german: 'Angesichts von Schwierigkeiten muessen wir zusammenhalten.' }] },
    { word: '反目成仇', pinyin: 'fǎn mù chéng chóu', meaning: 'sich entzweien und zu Feinden werden; zerstrittene Freunde', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们因为财产纠纷反目成仇。', pinyin: 'Tāmen yīnwèi cáichǎn jiūfēn fǎn mù chéng chóu.', german: 'Wegen eines Erbstreits wurden sie zu Feinden.' }] },
    { word: '天涯海角', pinyin: 'tiān yá hǎi jiǎo', meaning: 'am Ende der Welt; egal wie weit entfernt', type: 'Chengyu', level: 'HSK5', category: 'Beziehungen', examples: [{ chinese: '无论你在天涯海角，我都会想你。', pinyin: 'Wúlùn nǐ zài tiān yá hǎi jiǎo, wǒ dōu huì xiǎng nǐ.', german: 'Egal wo du auf der Welt bist, ich werde an dich denken.' }] },

    // ========================
    // === LERNEN ===
    // ========================

    { word: '好学不倦', pinyin: 'hào xué bù juàn', meaning: 'gerne und unermüdlich lernen; wissbegierig', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '她好学不倦，每天都看书到深夜。', pinyin: 'Tā hào xué bù juàn, měi tiān dōu kàn shū dào shēnyè.', german: 'Sie lernt unermüdlich und liest jeden Abend bis spät in die Nacht.' }] },
    { word: '日积月累', pinyin: 'rì jī yuè lěi', meaning: 'Tag fuer Tag, Monat fuer Monat ansammeln; stetige Anhaeuufung', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '学语言需要日积月累，不能急于求成。', pinyin: 'Xué yǔyán xūyào rì jī yuè lěi, bù néng jí yú qiú chéng.', german: 'Sprachen lernen erfordert stetige Anstrengung, man darf nicht auf schnelle Ergebnisse draengen.' }] },
    { word: '集腋成裘', pinyin: 'jí yè chéng qiú', meaning: 'Achselhaare sammeln, um einen Pelz zu machen; Kleinvieh macht auch Mist', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '每天背几个单词，集腋成裘，很快就能提高词汇量。', pinyin: 'Měi tiān bèi jǐ gè dāncí, jí yè chéng qiú, hěn kuài jiù néng tígāo cíhuìliàng.', german: 'Jeden Tag ein paar Vokabeln lernen, Kleinvieh macht auch Mist, bald verbessert sich der Wortschatz.' }] },
    { word: '悬梁刺股', pinyin: 'xuán liáng cì gǔ', meaning: 'sich das Haar an den Balken binden und sich in den Oberschenkel stechen; extrem fleissig studieren', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '他以悬梁刺股的精神刻苦学习。', pinyin: 'Tā yǐ xuán liáng cì gǔ de jīngshén kèkǔ xuéxí.', german: 'Er lernt mit dem Fleiss der alten Gelehrten, die sich die Haare am Balken festbanden.' }] },
    { word: '博学多才', pinyin: 'bó xué duō cái', meaning: 'umfassend gebildet und vielseitig begabt', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '他博学多才，什么话题都能聊。', pinyin: 'Tā bó xué duō cái, shénme huàtí dōu néng liáo.', german: 'Er ist umfassend gebildet und kann ueber jedes Thema mitreden.' }] },
    { word: '活到老学到老', pinyin: 'huó dào lǎo xué dào lǎo', meaning: 'leben bis ins Alter, lernen bis ins Alter; lebenslanges Lernen', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '奶奶八十岁还在学电脑，真是活到老学到老。', pinyin: 'Nǎinai bāshí suì hái zài xué diànnǎo, zhēn shì huó dào lǎo xué dào lǎo.', german: 'Grossmutter lernt mit achtzig noch den Computer — wirklich lebenslanges Lernen.' }] },
    { word: '学富五车', pinyin: 'xué fù wǔ chē', meaning: 'so viel Wissen wie fuenf Wagenladungen Buecher; sehr gelehrt', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '这位教授学富五车，受到学生们的尊敬。', pinyin: 'Zhè wèi jiàoshòu xué fù wǔ chē, shòu dào xuéshengmen de zūnjìng.', german: 'Dieser Professor ist aeusserst gelehrt und wird von den Studenten sehr respektiert.' }] },
    { word: '一窍不通', pinyin: 'yī qiào bù tōng', meaning: 'keinen einzigen Durchlass offen haben; absolut nichts verstehen', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '他对音乐一窍不通。', pinyin: 'Tā duì yīnyuè yī qiào bù tōng.', german: 'Er hat absolut keine Ahnung von Musik.' }] },
    { word: '勤学苦练', pinyin: 'qín xué kǔ liàn', meaning: 'fleissig lernen und hart ueben; eiserner Fleiss', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '想成为钢琴家，必须勤学苦练。', pinyin: 'Xiǎng chéngwéi gāngqínjiā, bìxū qín xué kǔ liàn.', german: 'Um Pianist zu werden, muss man fleissig lernen und hart ueben.' }] },
    { word: '才华横溢', pinyin: 'cái huá héng yì', meaning: 'das Talent fliesst ueber; aeusserst begabt', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '这位年轻作家才华横溢，前途无量。', pinyin: 'Zhè wèi niánqīng zuòjiā cái huá héng yì, qiántú wúliàng.', german: 'Dieser junge Autor ist aeusserst begabt und hat eine vielversprechende Zukunft.' }] },
    { word: '过目不忘', pinyin: 'guò mù bù wàng', meaning: 'einmal sehen und nie vergessen; fotografisches Gedaechtnis', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '她有过目不忘的本领，看过的东西都记得。', pinyin: 'Tā yǒu guò mù bù wàng de běnlǐng, kàn guò de dōngxi dōu jì de.', german: 'Sie hat ein fotografisches Gedaechtnis und erinnert sich an alles, was sie gesehen hat.' }] },
    { word: '按部就班', pinyin: 'àn bù jiù bān', meaning: 'Schritt fuer Schritt nach Plan vorgehen; methodisch', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '学习要按部就班，不要跳过基础。', pinyin: 'Xuéxí yào àn bù jiù bān, bù yào tiào guò jīchǔ.', german: 'Beim Lernen soll man Schritt fuer Schritt vorgehen und die Grundlagen nicht ueberspringen.' }] },

    // ========================
    // === GESCHICHTE ===
    // ========================

    { word: '围魏救赵', pinyin: 'wéi Wèi jiù Zhào', meaning: 'Wei belagern, um Zhao zu retten; den Gegner indirekt angreifen', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '这个策略就是围魏救赵，通过转移对手的注意力来取胜。', pinyin: 'Zhège cèlüè jiùshì wéi Wèi jiù Zhào, tōngguò zhuǎnyí duìshǒu de zhùyìlì lái qǔshèng.', german: 'Diese Strategie ist ein indirekter Angriff: den Gegner ablenken, um zu siegen.' }] },
    { word: '闻鸡起舞', pinyin: 'wén jī qǐ wǔ', meaning: 'beim Hahnenschrei aufstehen und das Schwert ueben; frueh aufstehen und fleissig trainieren', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他闻鸡起舞，每天天不亮就开始锻炼。', pinyin: 'Tā wén jī qǐ wǔ, měi tiān tiān bù liàng jiù kāishǐ duànliàn.', german: 'Er steht beim Hahnenschrei auf und beginnt jeden Tag vor der Daemmerung zu trainieren.' }] },
    { word: '退避三舍', pinyin: 'tuì bì sān shě', meaning: 'drei Tagesmaersche zurueckweichen; jemandem aus dem Weg gehen', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '面对他的坏脾气，大家都退避三舍。', pinyin: 'Miànduì tā de huài píqi, dàjiā dōu tuì bì sān shě.', german: 'Angesichts seines schlechten Temperaments gehen alle ihm aus dem Weg.' }] },
    { word: '暗渡陈仓', pinyin: 'àn dù Chén Cāng', meaning: 'heimlich den Chencang-Pass ueberqueren; eine Taeuschung anwenden', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他明修栈道，暗渡陈仓，成功完成了计划。', pinyin: 'Tā míng xiū zhàn dào, àn dù Chén Cāng, chénggōng wánchéng le jìhuà.', german: 'Er taeuschte offen vor und handelte heimlich — so setzte er seinen Plan erfolgreich um.' }] },
    { word: '草船借箭', pinyin: 'cǎo chuán jiè jiàn', meaning: 'mit Strohbooten Pfeile borgen; den Gegner ueberlisten', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他用草船借箭的策略，巧妙地解决了问题。', pinyin: 'Tā yòng cǎo chuán jiè jiàn de cèlüè, qiǎomiào de jiějué le wèntí.', german: 'Er nutzte eine listige Strategie und loeste das Problem auf geschickte Weise.' }] },
    { word: '毛遂自荐', pinyin: 'Máo Suì zì jiàn', meaning: 'sich selbst wie Mao Sui empfehlen; sich freiwillig melden', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他毛遂自荐，主动承担了这个项目。', pinyin: 'Tā Máo Suì zì jiàn, zhǔdòng chéngdān le zhège xiàngmù.', german: 'Er empfahl sich selbst und uebernahm freiwillig dieses Projekt.' }] },
    { word: '朝秦暮楚', pinyin: 'zhāo Qín mù Chǔ', meaning: 'morgens bei Qin, abends bei Chu; wankelmutig und unbestaendig', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他朝秦暮楚，让人无法信任。', pinyin: 'Tā zhāo Qín mù Chǔ, ràng rén wúfǎ xìnrèn.', german: 'Er wechselt staendig die Seite, sodass man ihm nicht vertrauen kann.' }] },
    { word: '画地为牢', pinyin: 'huà dì wéi láo', meaning: 'auf den Boden zeichnen und es zum Gefaengnis machen; sich selbst einschraenken', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '不要画地为牢，要勇于尝试新事物。', pinyin: 'Bù yào huà dì wéi láo, yào yǒngyú chángshì xīn shìwù.', german: 'Schraenke dich nicht selbst ein, wage es, Neues auszuprobieren.' }] },
    { word: '项庄舞剑', pinyin: 'Xiàng Zhuāng wǔ jiàn', meaning: 'Xiang Zhuang tanzt mit dem Schwert; eine verdeckte Absicht verfolgen', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他表面上在帮你，其实项庄舞剑，意在沛公。', pinyin: 'Tā biǎomiàn shàng zài bāng nǐ, qíshí Xiàng Zhuāng wǔ jiàn, yì zài Pèi Gōng.', german: 'Er tut so, als wuerde er dir helfen, verfolgt aber in Wahrheit eine verdeckte Absicht.' }] },
    { word: '老马识途', pinyin: 'lǎo mǎ shí tú', meaning: 'ein altes Pferd kennt den Weg; Erfahrung ist wertvoll', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '别担心，他是老马识途，一定能找到解决办法。', pinyin: 'Bié dānxīn, tā shì lǎo mǎ shí tú, yīdìng néng zhǎodào jiějué bànfǎ.', german: 'Keine Sorge, er ist erfahren wie ein altes Pferd und wird sicher eine Loesung finden.' }] },
    { word: '一箭双雕', pinyin: 'yī jiàn shuāng diāo', meaning: 'mit einem Pfeil zwei Adler treffen; zwei Fliegen mit einer Klappe', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '这个方案一箭双雕，既省钱又省时间。', pinyin: 'Zhège fāng\'àn yī jiàn shuāng diāo, jì shěng qián yòu shěng shíjiān.', german: 'Dieser Plan schlaegt zwei Fliegen mit einer Klappe: er spart Geld und Zeit.' }] },

    // ========================
    // === WARNUNG ===
    // ========================

    { word: '自投罗网', pinyin: 'zì tóu luó wǎng', meaning: 'sich selbst ins Netz werfen; ins eigene Verderben rennen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '他去警察局自首，等于自投罗网。', pinyin: 'Tā qù jǐngchájú zìshǒu, děngyú zì tóu luó wǎng.', german: 'Er ging zur Polizei und stellte sich, das war wie sich selbst ins Netz zu werfen.' }] },
    { word: '唇亡齿寒', pinyin: 'chún wáng chǐ hán', meaning: 'wenn die Lippen weg sind, frieren die Zaehne; gegenseitige Abhaengigkeit', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '这两个部门唇亡齿寒，一个倒了另一个也难保。', pinyin: 'Zhè liǎng gè bùmén chún wáng chǐ hán, yī gè dǎo le lìng yī gè yě nán bǎo.', german: 'Diese zwei Abteilungen sind voneinander abhaengig — faellt die eine, ist auch die andere in Gefahr.' }] },
    { word: '螳螂捕蝉', pinyin: 'táng láng bǔ chán', meaning: 'die Gottesanbeterin faengt die Zikade; nur das Naheliegende sehen und die Gefahr dahinter uebersehen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '螳螂捕蝉，黄雀在后。', pinyin: 'Táng láng bǔ chán, huáng què zài hòu.', german: 'Die Gottesanbeterin faengt die Zikade, aber der Pirolvogel lauert dahinter — Vorsicht vor verborgenen Gefahren.' }] },
    { word: '亡国之音', pinyin: 'wáng guó zhī yīn', meaning: 'Musik eines untergehenden Staates; Zeichen des Verfalls', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '公司内部矛盾重重，已有亡国之音。', pinyin: 'Gōngsī nèibù máodùn chóngchóng, yǐ yǒu wáng guó zhī yīn.', german: 'Das Unternehmen ist voller interner Konflikte, es gibt bereits Anzeichen des Niedergangs.' }] },
    { word: '坐以待毙', pinyin: 'zuò yǐ dài bì', meaning: 'sitzen und auf den Tod warten; tatenlos dem Untergang entgegensehen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '我们不能坐以待毙，必须主动想办法。', pinyin: 'Wǒmen bù néng zuò yǐ dài bì, bìxū zhǔdòng xiǎng bànfǎ.', german: 'Wir koennen nicht tatenlos zusehen, wir muessen aktiv nach Loesungen suchen.' }] },
    { word: '搬起石头砸自己的脚', pinyin: 'bān qǐ shítou zá zìjǐ de jiǎo', meaning: 'einen Stein heben und sich selbst auf den Fuss fallen lassen; sich selbst schaden', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '他造谣害人，最终搬起石头砸了自己的脚。', pinyin: 'Tā zào yáo hài rén, zuìzhōng bān qǐ shítou zá le zìjǐ de jiǎo.', german: 'Er verbreitete Geruechte, um anderen zu schaden, und schadete sich am Ende selbst.' }] },
    { word: '作茧自缚', pinyin: 'zuò jiǎn zì fù', meaning: 'einen Kokon spinnen und sich selbst einwickeln; sich in die eigene Falle locken', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '他制定了太多规则，结果作茧自缚。', pinyin: 'Tā zhìdìng le tài duō guīzé, jiéguǒ zuò jiǎn zì fù.', german: 'Er stellte zu viele Regeln auf und verfing sich schliesslich in seinen eigenen Regeln.' }] },
    { word: '引狼入室', pinyin: 'yǐn láng rù shì', meaning: 'den Wolf ins Haus fuehren; den Feind hereinlassen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '盲目信任陌生人，小心引狼入室。', pinyin: 'Mángmù xìnrèn mòshēng rén, xiǎoxīn yǐn láng rù shì.', german: 'Vertraue Fremden nicht blind, sonst laesst du den Wolf ins Haus.' }] },
    { word: '亡命之徒', pinyin: 'wáng mìng zhī tú', meaning: 'Gesetzloser; Desperado; jemand, der alles aufs Spiel setzt', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '不要和亡命之徒打交道，太危险了。', pinyin: 'Bù yào hé wáng mìng zhī tú dǎ jiāodào, tài wēixiǎn le.', german: 'Lass dich nicht mit Desperados ein, das ist zu gefaehrlich.' }] },
    { word: '覆水难收', pinyin: 'fù shuǐ nán shōu', meaning: 'verschuettetes Wasser laesst sich nicht zurueckholen; unwiderruflich', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '话已经说出去了，覆水难收。', pinyin: 'Huà yǐjīng shuō chūqù le, fù shuǐ nán shōu.', german: 'Die Worte sind gesagt, verschuettetes Wasser laesst sich nicht zurueckholen.' }] },
    { word: '鹤立鸡群', pinyin: 'hè lì jī qún', meaning: 'ein Kranich unter Huehnern; herausragend aus der Menge', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '他的才华让他鹤立鸡群，但也招来嫉妒。', pinyin: 'Tā de cáihuá ràng tā hè lì jī qún, dàn yě zhāo lái jídù.', german: 'Sein Talent laesst ihn aus der Menge herausragen, zieht aber auch Neid auf sich.' }] },
    { word: '趁火打劫', pinyin: 'chèn huǒ dǎ jié', meaning: 'waehrend des Brandes pluendern; die Not anderer ausnutzen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '灾难发生后，有人趁火打劫，哄抬物价。', pinyin: 'Zāinàn fāshēng hòu, yǒu rén chèn huǒ dǎ jié, hōngtái wùjià.', german: 'Nach der Katastrophe nutzten manche die Lage aus und trieben die Preise in die Hoehe.' }] },

    // ========================
    // === WEITERE MISCHUNG ===
    // ========================

    { word: '天长地久', pinyin: 'tiān cháng dì jiǔ', meaning: 'so lang wie der Himmel und so bestaendig wie die Erde; fuer immer', type: 'Chengyu', level: 'HSK5', category: 'Beziehungen', examples: [{ chinese: '他们的友谊天长地久。', pinyin: 'Tāmen de yǒuyì tiān cháng dì jiǔ.', german: 'Ihre Freundschaft waehrt ewig.' }] },
    { word: '苦尽甘来', pinyin: 'kǔ jìn gān lái', meaning: 'das Bittere ist vorbei, das Suesse kommt; nach dem Leid kommt das Glueck', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '经过多年的奋斗，他终于苦尽甘来了。', pinyin: 'Jīngguò duō nián de fèndòu, tā zhōngyú kǔ jìn gān lái le.', german: 'Nach vielen Jahren des Kampfes kam fuer ihn endlich die suesse Zeit.' }] },
    { word: '风平浪静', pinyin: 'fēng píng làng jìng', meaning: 'ruhiger Wind und stille Wellen; friedlich und ruhig', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '暴风雨过后，大海又恢复了风平浪静。', pinyin: 'Bàofēngyǔ guò hòu, dàhǎi yòu huīfù le fēng píng làng jìng.', german: 'Nach dem Sturm kehrte das Meer wieder zu Ruhe und Stille zurueck.' }] },
    { word: '叹为观止', pinyin: 'tàn wéi guān zhǐ', meaning: 'so beeindruckend, dass man nur noch staunen kann; atemberaubend', type: 'Chengyu', level: 'HSK6', category: 'Gefuehle', examples: [{ chinese: '这场演出令人叹为观止。', pinyin: 'Zhè chǎng yǎnchū lìng rén tàn wéi guān zhǐ.', german: 'Diese Vorfuehrung war atemberaubend.' }] },
    { word: '一马当先', pinyin: 'yī mǎ dāng xiān', meaning: 'ein Pferd voraus; als Erster vorangehen', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '他总是一马当先，带领团队完成任务。', pinyin: 'Tā zǒng shì yī mǎ dāng xiān, dàilǐng tuánduì wánchéng rènwù.', german: 'Er geht immer als Erster voran und fuehrt das Team zur Erfuellung der Aufgabe.' }] },
    { word: '刻不容缓', pinyin: 'kè bù róng huǎn', meaning: 'keinen Augenblick Aufschub dulden; aeusserst dringend', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '这件事刻不容缓，必须立刻处理。', pinyin: 'Zhè jiàn shì kè bù róng huǎn, bìxū lìkè chǔlǐ.', german: 'Diese Angelegenheit duldet keinen Aufschub und muss sofort erledigt werden.' }] },
    { word: '不可救药', pinyin: 'bù kě jiù yào', meaning: 'durch keine Medizin mehr zu retten; hoffnungslos', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '他的懒惰已经到了不可救药的地步。', pinyin: 'Tā de lǎnduò yǐjīng dào le bù kě jiù yào de dìbù.', german: 'Seine Faulheit hat ein hoffnungsloses Ausmass erreicht.' }] },
    { word: '天经地义', pinyin: 'tiān jīng dì yì', meaning: 'so natuerlich wie die Gesetze des Himmels und der Erde; selbstverstaendlich', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '孝敬父母是天经地义的事。', pinyin: 'Xiàojìng fùmǔ shì tiān jīng dì yì de shì.', german: 'Die Eltern zu ehren ist eine Selbstverstaendlichkeit.' }] },
    { word: '言不由衷', pinyin: 'yán bù yóu zhōng', meaning: 'die Worte kommen nicht aus dem Herzen; nicht meinen, was man sagt', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他的道歉让人觉得言不由衷。', pinyin: 'Tā de dàoqiàn ràng rén juéde yán bù yóu zhōng.', german: 'Seine Entschuldigung wirkte nicht aufrichtig.' }] },
    { word: '雷厉风行', pinyin: 'léi lì fēng xíng', meaning: 'wie Donner und Wind; entschlossen und tatkraeftig handeln', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '新领导雷厉风行，上任就开始改革。', pinyin: 'Xīn lǐngdǎo léi lì fēng xíng, shàngrèn jiù kāishǐ gǎigé.', german: 'Der neue Chef handelt entschlossen und begann sofort nach Amtsantritt mit Reformen.' }] },
    { word: '柳暗花明', pinyin: 'liǔ àn huā míng', meaning: 'dunkle Weiden und helle Blumen; eine ueberraschende Wendung zum Guten', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '正当他要放弃时，柳暗花明，找到了新的出路。', pinyin: 'Zhèng dāng tā yào fàngqì shí, liǔ àn huā míng, zhǎodào le xīn de chūlù.', german: 'Gerade als er aufgeben wollte, wendete sich alles ueberraschend zum Guten und er fand einen neuen Ausweg.' }] },
    { word: '谈笑风生', pinyin: 'tán xiào fēng shēng', meaning: 'plaudern und lachen, dass der Wind entsteht; lebhaft und heiter plaudern', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们谈笑风生，聚会非常愉快。', pinyin: 'Tāmen tán xiào fēng shēng, jùhuì fēicháng yúkuài.', german: 'Sie plauderten und lachten heiter, das Treffen war sehr angenehm.' }] },
    { word: '泰然自若', pinyin: 'tài rán zì ruò', meaning: 'ruhig und gelassen wie immer; voellig unbeeindruckt', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '面对巨大压力，她依然泰然自若。', pinyin: 'Miànduì jùdà yālì, tā yīrán tài rán zì ruò.', german: 'Trotz enormem Druck blieb sie voellig gelassen.' }] },
    { word: '见微知著', pinyin: 'jiàn wēi zhī zhù', meaning: 'aus kleinen Anzeichen das Grosse erkennen; aufmerksam und vorausschauend', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '好的分析师能见微知著，提前预判趋势。', pinyin: 'Hǎo de fēnxīshī néng jiàn wēi zhī zhù, tíqián yùpàn qūshì.', german: 'Ein guter Analyst erkennt aus kleinen Anzeichen grosse Trends im Voraus.' }] },
    { word: '安然无恙', pinyin: 'ān rán wú yàng', meaning: 'wohlbehalten und unbeschaedigt; ohne jeden Schaden', type: 'Chengyu', level: 'HSK5', category: 'Gefuehle', examples: [{ chinese: '地震之后，他安然无恙，家人很放心。', pinyin: 'Dìzhèn zhīhòu, tā ān rán wú yàng, jiārén hěn fàngxīn.', german: 'Nach dem Erdbeben war er wohlbehalten und die Familie war erleichtert.' }] },
    { word: '名落孙山', pinyin: 'míng luò Sūn Shān', meaning: 'hinter Sun Shan auf der Liste stehen; die Pruefung nicht bestehen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '他这次考试名落孙山，非常失望。', pinyin: 'Tā zhè cì kǎoshì míng luò Sūn Shān, fēicháng shīwàng.', german: 'Er ist bei dieser Pruefung durchgefallen und sehr enttaeuscht.' }] },
    { word: '言传身教', pinyin: 'yán chuán shēn jiào', meaning: 'mit Worten lehren und durch Vorbild erziehen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '父母的言传身教对孩子的成长非常重要。', pinyin: 'Fùmǔ de yán chuán shēn jiào duì háizi de chéngzhǎng fēicháng zhòngyào.', german: 'Das Lehren durch Worte und Vorbild der Eltern ist fuer die Entwicklung der Kinder sehr wichtig.' }] },
    { word: '无独有偶', pinyin: 'wú dú yǒu ǒu', meaning: 'nicht einzeln, sondern paarweise; zufaelligerweise nicht der einzige Fall', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '无独有偶，隔壁公司也遇到了同样的问题。', pinyin: 'Wú dú yǒu ǒu, gébì gōngsī yě yù dào le tóngyàng de wèntí.', german: 'Zufaelligerweise hatte auch das Nachbarunternehmen das gleiche Problem.' }] },
    { word: '前功尽弃', pinyin: 'qián gōng jìn qì', meaning: 'alle bisherige Muehe umsonst; den bisherigen Erfolg zunichte machen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '现在放弃的话，之前的努力就前功尽弃了。', pinyin: 'Xiànzài fàngqì de huà, zhīqián de nǔlì jiù qián gōng jìn qì le.', german: 'Wenn du jetzt aufgibst, war die ganze bisherige Muehe umsonst.' }] },
    { word: '耳濡目染', pinyin: 'ěr rú mù rǎn', meaning: 'durch Hoeren und Sehen beeinflusst werden; unbewusst lernen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '在音乐世家长大，他耳濡目染，从小就会弹琴。', pinyin: 'Zài yīnyuè shìjiā zhǎng dà, tā ěr rú mù rǎn, cóng xiǎo jiù huì tán qín.', german: 'In einer Musikerfamilie aufgewachsen, lernte er durchs Zuhoeren und Zusehen schon als Kind Klavier.' }] },
    { word: '厉兵秣马', pinyin: 'lì bīng mò mǎ', meaning: 'die Waffen schaerfen und die Pferde fuettern; sich auf den Kampf vorbereiten', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '比赛前夕，队员们厉兵秣马，做好充分准备。', pinyin: 'Bǐsài qián xī, duìyuánmen lì bīng mò mǎ, zuò hǎo chōngfèn zhǔnbèi.', german: 'Am Vorabend des Wettkampfs bereitete sich das Team gruendlich vor.' }] },
    { word: '人山人海', pinyin: 'rén shān rén hǎi', meaning: 'ein Meer von Menschen; riesige Menschenmenge', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '国庆节长城上人山人海。', pinyin: 'Guóqìngjié Chángchéng shàng rén shān rén hǎi.', german: 'Am Nationalfeiertag ist die Grosse Mauer ein Meer von Menschen.' }] },
    { word: '谨小慎微', pinyin: 'jǐn xiǎo shèn wēi', meaning: 'in kleinen Dingen vorsichtig und behutsam; aeusserst umsichtig', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他做事谨小慎微，从不犯低级错误。', pinyin: 'Tā zuòshì jǐn xiǎo shèn wēi, cóng bù fàn dījí cuòwù.', german: 'Er handelt aeusserst umsichtig und macht nie leichtfertige Fehler.' }] },
    { word: '势如破竹', pinyin: 'shì rú pò zhú', meaning: 'wie Bambus spalten; unaufhaltsam voranschreiten', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '我军势如破竹，一路向前推进。', pinyin: 'Wǒ jūn shì rú pò zhú, yī lù xiàng qián tuījìn.', german: 'Unsere Truppen schritten unaufhaltsam voran und rueckten staendig vor.' }] },
    { word: '恍然大悟', pinyin: 'huǎng rán dà wù', meaning: 'ploetzlich erleuchtet werden; den Aha-Moment erleben', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '经老师一讲，他恍然大悟。', pinyin: 'Jīng lǎoshī yī jiǎng, tā huǎng rán dà wù.', german: 'Nach der Erklaerung des Lehrers hatte er ploetzlich den Aha-Moment.' }] },
    { word: '无价之宝', pinyin: 'wú jià zhī bǎo', meaning: 'ein unbezahlbarer Schatz; von unschaetzbarem Wert', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '健康是无价之宝，要好好珍惜。', pinyin: 'Jiànkāng shì wú jià zhī bǎo, yào hǎohao zhēnxī.', german: 'Gesundheit ist ein unbezahlbarer Schatz, den man hueten sollte.' }] },
    { word: '同心协力', pinyin: 'tóng xīn xié lì', meaning: 'mit vereintem Herzen und vereinter Kraft; gemeinsam an einem Strang ziehen', type: 'Chengyu', level: 'HSK5', category: 'Beziehungen', examples: [{ chinese: '只有同心协力，我们才能克服困难。', pinyin: 'Zhǐyǒu tóng xīn xié lì, wǒmen cái néng kèfú kùnnán.', german: 'Nur wenn wir gemeinsam an einem Strang ziehen, koennen wir die Schwierigkeiten ueberwinden.' }] },
    { word: '乘风破浪', pinyin: 'chéng fēng pò làng', meaning: 'mit dem Wind die Wellen brechen; kuehne Ziele verfolgen', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '年轻人应该乘风破浪，追求自己的梦想。', pinyin: 'Niánqīng rén yīnggāi chéng fēng pò làng, zhuīqiú zìjǐ de mèngxiǎng.', german: 'Junge Menschen sollen kuehn die Wellen brechen und ihre Traeume verfolgen.' }] },

  ]);
})();
