// Chengyu (成语) — Four-character idioms
// Chinesische Vier-Zeichen-Redewendungen fuer deutschsprachige Lernende
// UI-Sprache: Deutsch

(function () {
  var chengyu = [

    // ========================
    // === LEBENSWEISHEIT ===
    // ========================

    { word: '一举两得', pinyin: 'yī jǔ liǎng dé', meaning: 'zwei Fliegen mit einer Klappe schlagen', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '学中文的同时还能了解中国文化，真是一举两得。', pinyin: 'Xué zhōngwén de tóngshí hái néng liǎojiě zhōngguó wénhuà, zhēn shì yī jǔ liǎng dé.', german: 'Beim Chinesischlernen gleichzeitig die chinesische Kultur kennenzulernen, das ist wirklich zwei Fliegen mit einer Klappe.' }] },
    { word: '塞翁失马', pinyin: 'sài wēng shī mǎ', meaning: 'ein Unglueck kann sich als Segen erweisen', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '虽然他丢了工作，但后来找到了更好的，真是塞翁失马。', pinyin: 'Suīrán tā diū le gōngzuò, dàn hòulái zhǎodào le gèng hǎo de, zhēn shì sài wēng shī mǎ.', german: 'Er hat zwar seine Arbeit verloren, aber danach eine bessere gefunden — ein Unglueck kann sich als Segen erweisen.' }] },
    { word: '亡羊补牢', pinyin: 'wáng yáng bǔ láo', meaning: 'besser spaet als nie; den Stall reparieren, nachdem das Schaf verloren ist', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '虽然已经犯了错误，但亡羊补牢，为时未晚。', pinyin: 'Suīrán yǐjīng fàn le cuòwù, dàn wáng yáng bǔ láo, wéi shí wèi wǎn.', german: 'Obwohl schon ein Fehler gemacht wurde, ist es noch nicht zu spaet, ihn zu korrigieren.' }] },
    { word: '入乡随俗', pinyin: 'rù xiāng suí sú', meaning: 'andere Laender, andere Sitten; sich anpassen', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '到了中国就要入乡随俗，学会用筷子吃饭。', pinyin: 'Dào le zhōngguó jiù yào rù xiāng suí sú, xuéhuì yòng kuàizi chīfàn.', german: 'Wenn man in China ist, sollte man sich anpassen und lernen, mit Staebchen zu essen.' }] },
    { word: '知足常乐', pinyin: 'zhī zú cháng lè', meaning: 'wer zufrieden ist, ist immer gluecklich', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '人要学会知足常乐，不要总是跟别人比较。', pinyin: 'Rén yào xuéhuì zhī zú cháng lè, bù yào zǒng shì gēn biéren bǐjiào.', german: 'Man sollte lernen, mit dem zufrieden zu sein, was man hat, und sich nicht staendig mit anderen vergleichen.' }] },
    { word: '三思而行', pinyin: 'sān sī ér xíng', meaning: 'dreimal ueberlegen, bevor man handelt', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '做重大决定之前，一定要三思而行。', pinyin: 'Zuò zhòngdà juédìng zhīqián, yīdìng yào sān sī ér xíng.', german: 'Bevor man eine wichtige Entscheidung trifft, muss man gruendlich nachdenken.' }] },
    { word: '水滴石穿', pinyin: 'shuǐ dī shí chuān', meaning: 'steter Tropfen hoehlt den Stein', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '只要坚持努力，水滴石穿，一定能成功。', pinyin: 'Zhǐyào jiānchí nǔlì, shuǐ dī shí chuān, yīdìng néng chénggōng.', german: 'Solange man beharrlich ist, wird steter Tropfen den Stein hoehlen und man wird Erfolg haben.' }] },
    { word: '因小失大', pinyin: 'yīn xiǎo shī dà', meaning: 'wegen einer Kleinigkeit Grosses verlieren', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '不要因小失大，为了省几块钱买便宜货。', pinyin: 'Bù yào yīn xiǎo shī dà, wèile shěng jǐ kuài qián mǎi piányi huò.', german: 'Verliere nicht das Grosse wegen des Kleinen, indem du fuer ein paar Euro billige Ware kaufst.' }] },
    { word: '未雨绸缪', pinyin: 'wèi yǔ chóu móu', meaning: 'Vorsorge treffen; sich rechtzeitig vorbereiten', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '我们应该未雨绸缪，提前做好准备。', pinyin: 'Wǒmen yīnggāi wèi yǔ chóu móu, tíqián zuò hǎo zhǔnbèi.', german: 'Wir sollten vorsorgen und uns rechtzeitig vorbereiten.' }] },
    { word: '居安思危', pinyin: 'jū ān sī wēi', meaning: 'in sicheren Zeiten an moegliche Gefahren denken', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '企业发展顺利的时候也要居安思危。', pinyin: 'Qǐyè fāzhǎn shùnlì de shíhou yě yào jū ān sī wēi.', german: 'Auch wenn das Unternehmen gut laeuft, sollte man an moegliche Risiken denken.' }] },
    { word: '物极必反', pinyin: 'wù jí bì fǎn', meaning: 'wenn etwas sein Extrem erreicht, schlaegt es ins Gegenteil um', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '压力太大会适得其反，物极必反嘛。', pinyin: 'Yālì tài dà huì shìdéqífǎn, wù jí bì fǎn ma.', german: 'Zu viel Druck bewirkt das Gegenteil — alles schlaegt irgendwann um.' }] },
    { word: '前车之鉴', pinyin: 'qián chē zhī jiàn', meaning: 'aus den Fehlern anderer lernen', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '他的失败是我们的前车之鉴，我们不能再犯同样的错误。', pinyin: 'Tā de shībài shì wǒmen de qián chē zhī jiàn, wǒmen bù néng zài fàn tóngyàng de cuòwù.', german: 'Sein Scheitern ist eine Warnung fuer uns, wir duerfen nicht denselben Fehler machen.' }] },
    { word: '量力而行', pinyin: 'liàng lì ér xíng', meaning: 'nach seinen Kraeften handeln; sich nicht uebernehmen', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '运动要量力而行，不要勉强自己。', pinyin: 'Yùndòng yào liàng lì ér xíng, bù yào miǎnqiǎng zìjǐ.', german: 'Beim Sport sollte man nach seinen Kraeften handeln und sich nicht ueberanstrengen.' }] },
    { word: '随遇而安', pinyin: 'suí yù ér ān', meaning: 'sich den Umstaenden anpassen; nehmen, wie es kommt', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '他是一个随遇而安的人，从不抱怨生活。', pinyin: 'Tā shì yī gè suí yù ér ān de rén, cóng bù bàoyuàn shēnghuó.', german: 'Er ist jemand, der die Dinge nimmt, wie sie kommen, und sich nie ueber das Leben beschwert.' }] },
    { word: '见仁见智', pinyin: 'jiàn rén jiàn zhì', meaning: 'jeder sieht es anders; Ansichtssache', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '这个问题见仁见智，没有标准答案。', pinyin: 'Zhège wèntí jiàn rén jiàn zhì, méiyǒu biāozhǔn dá\'àn.', german: 'Diese Frage ist Ansichtssache, es gibt keine Standardantwort.' }] },
    { word: '取长补短', pinyin: 'qǔ cháng bǔ duǎn', meaning: 'die Staerken nutzen, um die Schwaechen auszugleichen', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '团队合作的关键是取长补短。', pinyin: 'Tuánduì hézuò de guānjiàn shì qǔ cháng bǔ duǎn.', german: 'Der Schluessel zur Teamarbeit ist, die Staerken zu nutzen und die Schwaechen auszugleichen.' }] },
    { word: '实事求是', pinyin: 'shí shì qiú shì', meaning: 'die Wahrheit in den Tatsachen suchen; sachlich und realistisch sein', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '做研究要实事求是，不能弄虚作假。', pinyin: 'Zuò yánjiū yào shí shì qiú shì, bù néng nòng xū zuò jiǎ.', german: 'Bei der Forschung muss man sachlich vorgehen und darf nicht faelschen.' }] },
    { word: '以身作则', pinyin: 'yǐ shēn zuò zé', meaning: 'mit gutem Beispiel vorangehen', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '好的领导应该以身作则。', pinyin: 'Hǎo de lǐngdǎo yīnggāi yǐ shēn zuò zé.', german: 'Eine gute Fuehrungskraft sollte mit gutem Beispiel vorangehen.' }] },
    { word: '一视同仁', pinyin: 'yī shì tóng rén', meaning: 'alle gleich behandeln; ohne Ansehen der Person', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '老师对学生应该一视同仁。', pinyin: 'Lǎoshī duì xuéshēng yīnggāi yī shì tóng rén.', german: 'Lehrer sollten alle Schueler gleich behandeln.' }] },
    { word: '己所不欲勿施于人', pinyin: 'jǐ suǒ bù yù wù shī yú rén', meaning: 'was du nicht willst, das man dir tu, das fueg auch keinem andern zu', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '己所不欲勿施于人，这是做人的基本道理。', pinyin: 'Jǐ suǒ bù yù wù shī yú rén, zhè shì zuòrén de jīběn dàolǐ.', german: 'Was du nicht willst, das man dir tu, das fueg auch keinem andern zu — das ist eine grundlegende Lebensregel.' }] },

    // ========================
    // === CHARAKTER ===
    // ========================

    { word: '自言自语', pinyin: 'zì yán zì yǔ', meaning: 'Selbstgespraeche fuehren; mit sich selbst reden', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '他总是自言自语，好像在跟自己说话。', pinyin: 'Tā zǒng shì zì yán zì yǔ, hǎoxiàng zài gēn zìjǐ shuōhuà.', german: 'Er fuehrt staendig Selbstgespraeche, als wuerde er mit sich selbst reden.' }] },
    { word: '心直口快', pinyin: 'xīn zhí kǒu kuài', meaning: 'aufrichtig und freimuetig; sagen, was man denkt', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '她是个心直口快的人，从来不拐弯抹角。', pinyin: 'Tā shì gè xīn zhí kǒu kuài de rén, cónglái bù guǎiwān mò jiǎo.', german: 'Sie ist ein aufrichtiger Mensch und redet nie um den heissen Brei.' }] },
    { word: '自以为是', pinyin: 'zì yǐ wéi shì', meaning: 'eingebildet sein; sich fuer unfehlbar halten', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '他太自以为是了，从来不听别人的意见。', pinyin: 'Tā tài zì yǐ wéi shì le, cónglái bù tīng biéren de yìjiàn.', german: 'Er ist zu eingebildet und hoert nie auf die Meinung anderer.' }] },
    { word: '一心一意', pinyin: 'yī xīn yī yì', meaning: 'mit ganzem Herzen; hingebungsvoll', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '她一心一意地照顾生病的母亲。', pinyin: 'Tā yī xīn yī yì de zhàogù shēngbìng de mǔqīn.', german: 'Sie kuemmert sich hingebungsvoll um ihre kranke Mutter.' }] },
    { word: '小心翼翼', pinyin: 'xiǎo xīn yì yì', meaning: 'aeusserst vorsichtig; mit groesster Sorgfalt', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '他小心翼翼地端着那杯热茶。', pinyin: 'Tā xiǎo xīn yì yì de duān zhe nà bēi rè chá.', german: 'Er traegt die heisse Teetasse mit groesster Vorsicht.' }] },
    { word: '落落大方', pinyin: 'luò luò dà fāng', meaning: 'natuerlich und unbefangen; selbstsicher auftreten', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '她在舞台上落落大方，一点也不紧张。', pinyin: 'Tā zài wǔtái shàng luò luò dà fāng, yīdiǎn yě bù jǐnzhāng.', german: 'Sie tritt auf der Buehne voellig unbefangen auf, ohne jede Nervositaet.' }] },
    { word: '毫不犹豫', pinyin: 'háo bù yóuyù', meaning: 'ohne zu zoegern; ohne jedes Bedenken', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '他毫不犹豫地跳进水里救人。', pinyin: 'Tā háo bù yóuyù de tiào jìn shuǐ lǐ jiù rén.', german: 'Er sprang ohne zu zoegern ins Wasser, um den Menschen zu retten.' }] },
    { word: '斤斤计较', pinyin: 'jīn jīn jì jiào', meaning: 'kleinlich sein; alles auf die Goldwaage legen', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '做人不要太斤斤计较，要大方一些。', pinyin: 'Zuòrén bù yào tài jīn jīn jì jiào, yào dàfāng yīxiē.', german: 'Man sollte nicht so kleinlich sein, sondern etwas grosszuegiger.' }] },
    { word: '见义勇为', pinyin: 'jiàn yì yǒng wéi', meaning: 'mutig fuer das Richtige eintreten; Zivilcourage zeigen', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '那位见义勇为的年轻人受到了表扬。', pinyin: 'Nà wèi jiàn yì yǒng wéi de niánqīng rén shòudào le biǎoyáng.', german: 'Der mutige junge Mann, der Zivilcourage gezeigt hat, wurde gelobt.' }] },
    { word: '光明磊落', pinyin: 'guāng míng lěi luò', meaning: 'aufrichtig und ehrlich; integer', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他做事光明磊落，从来不搞小动作。', pinyin: 'Tā zuòshì guāng míng lěi luò, cónglái bù gǎo xiǎo dòngzuò.', german: 'Er handelt stets aufrichtig und betreibt nie Hinterhaeltigkeiten.' }] },
    { word: '任劳任怨', pinyin: 'rèn láo rèn yuàn', meaning: 'arbeitsam und klaglos; ohne zu murren', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '她任劳任怨地工作了三十年。', pinyin: 'Tā rèn láo rèn yuàn de gōngzuò le sānshí nián.', german: 'Sie hat dreissig Jahre lang ohne zu murren gearbeitet.' }] },
    { word: '目中无人', pinyin: 'mù zhōng wú rén', meaning: 'arrogant; ueberheblich; niemanden beachten', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他一当上经理就目中无人了。', pinyin: 'Tā yī dāng shàng jīnglǐ jiù mù zhōng wú rén le.', german: 'Kaum wurde er Manager, da wurde er sofort ueberheblich.' }] },
    { word: '胸有成竹', pinyin: 'xiōng yǒu chéng zhú', meaning: 'einen festen Plan im Kopf haben; gut vorbereitet sein', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他回答问题时胸有成竹，一点也不紧张。', pinyin: 'Tā huídá wèntí shí xiōng yǒu chéng zhú, yīdiǎn yě bù jǐnzhāng.', german: 'Er beantwortete die Fragen selbstsicher, ganz ohne Nervositaet.' }] },
    { word: '乐善好施', pinyin: 'lè shàn hào shī', meaning: 'wohltaetig und grosszuegig; gerne Gutes tun', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '这位老人乐善好施，经常帮助贫困家庭。', pinyin: 'Zhè wèi lǎorén lè shàn hào shī, jīngcháng bāngzhù pínkùn jiātíng.', german: 'Der alte Mann ist wohltaetig und hilft oft armen Familien.' }] },
    { word: '固执己见', pinyin: 'gù zhí jǐ jiàn', meaning: 'starrsinnig an der eigenen Meinung festhalten', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他太固执己见了，根本听不进别人的话。', pinyin: 'Tā tài gù zhí jǐ jiàn le, gēnběn tīng bù jìn biéren de huà.', german: 'Er ist so starrsinnig, dass er ueberhaupt nicht auf andere hoert.' }] },

    // ========================
    // === NATUR ===
    // ========================

    { word: '风和日丽', pinyin: 'fēng hé rì lì', meaning: 'schoenes Wetter mit sanftem Wind und Sonnenschein', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '今天风和日丽，我们去公园散步吧。', pinyin: 'Jīntiān fēng hé rì lì, wǒmen qù gōngyuán sànbù ba.', german: 'Heute ist schoenes Wetter, lass uns im Park spazieren gehen.' }] },
    { word: '山清水秀', pinyin: 'shān qīng shuǐ xiù', meaning: 'gruene Berge und klares Wasser; malerische Landschaft', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '这个地方山清水秀，非常适合度假。', pinyin: 'Zhège dìfāng shān qīng shuǐ xiù, fēicháng shìhé dùjià.', german: 'Dieser Ort hat eine malerische Landschaft und eignet sich sehr gut fuer Urlaub.' }] },
    { word: '鸟语花香', pinyin: 'niǎo yǔ huā xiāng', meaning: 'Vogelgezwitscher und Blumenduft; wunderbare Fruehlingsatmosphaere', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '春天来了，到处鸟语花香。', pinyin: 'Chūntiān lái le, dàochù niǎo yǔ huā xiāng.', german: 'Der Fruehling ist da, ueberall zwitschern Voegel und duften Blumen.' }] },
    { word: '万紫千红', pinyin: 'wàn zǐ qiān hóng', meaning: 'in tausend Farben bluehend; ueberaus bunt', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '春天的花园万紫千红，美不胜收。', pinyin: 'Chūntiān de huāyuán wàn zǐ qiān hóng, měi bù shèng shōu.', german: 'Der Garten im Fruehling blueht in tausend Farben, die Schoenheit ist ueberwael­tigend.' }] },
    { word: '翻山越岭', pinyin: 'fān shān yuè lǐng', meaning: 'ueber Berge und Huegel klettern; grosse Strapazen auf sich nehmen', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '为了到达那个村庄，他们翻山越岭走了三天。', pinyin: 'Wèile dàodá nàge cūnzhuāng, tāmen fān shān yuè lǐng zǒu le sān tiān.', german: 'Um das Dorf zu erreichen, sind sie drei Tage lang ueber Berge und Huegel gewandert.' }] },
    { word: '冰天雪地', pinyin: 'bīng tiān xuě dì', meaning: 'eisige Kaelte; Land aus Eis und Schnee', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '冬天的东北冰天雪地，非常寒冷。', pinyin: 'Dōngtiān de dōngběi bīng tiān xuě dì, fēicháng hánlěng.', german: 'Der Nordosten ist im Winter eine Welt aus Eis und Schnee, extrem kalt.' }] },
    { word: '春暖花开', pinyin: 'chūn nuǎn huā kāi', meaning: 'der Fruehling ist warm und die Blumen bluehen', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '春暖花开的季节最适合出去旅游。', pinyin: 'Chūn nuǎn huā kāi de jìjié zuì shìhé chūqù lǚyóu.', german: 'Die Jahreszeit, in der der Fruehling warm ist und die Blumen bluehen, eignet sich am besten zum Reisen.' }] },
    { word: '狂风暴雨', pinyin: 'kuáng fēng bào yǔ', meaning: 'heftiger Sturm und Regen; Unwetter', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '昨天晚上狂风暴雨，很多树都被刮倒了。', pinyin: 'Zuótiān wǎnshàng kuáng fēng bào yǔ, hěn duō shù dōu bèi guā dǎo le.', german: 'Gestern Nacht gab es ein heftiges Unwetter und viele Baeume wurden umgeweht.' }] },
    { word: '天翻地覆', pinyin: 'tiān fān dì fù', meaning: 'himmelumstürzend; gewaltige Veraenderung', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '这座城市发生了天翻地覆的变化。', pinyin: 'Zhè zuò chéngshì fāshēng le tiān fān dì fù de biànhuà.', german: 'Diese Stadt hat gewaltige Veraenderungen erlebt.' }] },
    { word: '满山遍野', pinyin: 'mǎn shān biàn yě', meaning: 'ueberall auf Bergen und Feldern; soweit das Auge reicht', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '秋天的时候，满山遍野都是红叶。', pinyin: 'Qiūtiān de shíhou, mǎn shān biàn yě dōu shì hóngyè.', german: 'Im Herbst sind die Berge und Felder ueberall mit rotem Laub bedeckt.' }] },

    // ========================
    // === ERFOLG ===
    // ========================

    { word: '半途而废', pinyin: 'bàn tú ér fèi', meaning: 'auf halbem Weg aufgeben; etwas nicht zu Ende bringen', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '学习不能半途而废，要坚持到底。', pinyin: 'Xuéxí bù néng bàn tú ér fèi, yào jiānchí dào dǐ.', german: 'Beim Lernen darf man nicht auf halbem Weg aufgeben, man muss durchhalten.' }] },
    { word: '一帆风顺', pinyin: 'yī fān fēng shùn', meaning: 'glatten Segelwind haben; alles laeuft glatt', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '祝你新的一年一帆风顺！', pinyin: 'Zhù nǐ xīn de yī nián yī fān fēng shùn!', german: 'Ich wuensche dir ein neues Jahr, in dem alles glatt laeuft!' }] },
    { word: '功成名就', pinyin: 'gōng chéng míng jiù', meaning: 'Erfolg und Ruhm erlangt haben', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '他功成名就之后，依然保持谦虚。', pinyin: 'Tā gōng chéng míng jiù zhīhòu, yīrán bǎochí qiānxū.', german: 'Selbst nachdem er Erfolg und Ruhm erlangt hatte, blieb er bescheiden.' }] },
    { word: '脚踏实地', pinyin: 'jiǎo tà shí dì', meaning: 'mit beiden Beinen auf dem Boden stehen; solide arbeiten', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '要想成功，就要脚踏实地，一步一步来。', pinyin: 'Yào xiǎng chénggōng, jiù yào jiǎo tà shí dì, yī bù yī bù lái.', german: 'Wer Erfolg haben will, muss mit beiden Beinen auf dem Boden stehen und Schritt fuer Schritt vorgehen.' }] },
    { word: '马到成功', pinyin: 'mǎ dào chéng gōng', meaning: 'sofortiger Erfolg; auf Anhieb gelingen', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '祝你考试马到成功！', pinyin: 'Zhù nǐ kǎoshì mǎ dào chéng gōng!', german: 'Ich wuensche dir, dass die Pruefung auf Anhieb gelingt!' }] },
    { word: '名不虚传', pinyin: 'míng bù xū chuán', meaning: 'der Ruf ist nicht uebertrieben; haelt, was es verspricht', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '这家餐厅果然名不虚传，菜真的很好吃。', pinyin: 'Zhè jiā cāntīng guǒrán míng bù xū chuán, cài zhēn de hěn hǎochī.', german: 'Das Restaurant haelt tatsaechlich, was sein Ruf verspricht, das Essen ist wirklich koestlich.' }] },
    { word: '锲而不舍', pinyin: 'qiè ér bù shě', meaning: 'beharrlich und unentschlossen; nicht aufgeben', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '锲而不舍，金石可镂。', pinyin: 'Qiè ér bù shě, jīn shí kě lòu.', german: 'Mit Beharrlichkeit kann man selbst Metall und Stein durchdringen.' }] },
    { word: '事半功倍', pinyin: 'shì bàn gōng bèi', meaning: 'mit halbem Aufwand doppelten Erfolg erzielen', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '掌握好方法就能事半功倍。', pinyin: 'Zhǎngwò hǎo fāngfǎ jiù néng shì bàn gōng bèi.', german: 'Mit der richtigen Methode erzielt man doppelten Erfolg mit halbem Aufwand.' }] },
    { word: '出人头地', pinyin: 'chū rén tóu dì', meaning: 'sich hervortun; es zu etwas bringen', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '他从小就立志要出人头地。', pinyin: 'Tā cóng xiǎo jiù lìzhì yào chū rén tóu dì.', german: 'Schon als Kind hat er sich vorgenommen, es zu etwas zu bringen.' }] },
    { word: '名列前茅', pinyin: 'míng liè qián máo', meaning: 'unter den Besten sein; an der Spitze stehen', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '她的成绩在班里总是名列前茅。', pinyin: 'Tā de chéngjì zài bān lǐ zǒng shì míng liè qián máo.', german: 'Ihre Noten gehoeren in der Klasse immer zu den besten.' }] },
    { word: '百折不挠', pinyin: 'bǎi zhé bù náo', meaning: 'sich durch nichts entmutigen lassen; unbeugsam', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '他百折不挠，终于实现了自己的梦想。', pinyin: 'Tā bǎi zhé bù náo, zhōngyú shíxiàn le zìjǐ de mèngxiǎng.', german: 'Er liess sich durch nichts entmutigen und verwirklichte schliesslich seinen Traum.' }] },
    { word: '大器晚成', pinyin: 'dà qì wǎn chéng', meaning: 'grosse Talente brauchen Zeit zur Entfaltung; Spaetzuender', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '不要着急，大器晚成，你的时代会来的。', pinyin: 'Bù yào zhāojí, dà qì wǎn chéng, nǐ de shídài huì lái de.', german: 'Sei nicht ungeduldig, grosse Talente brauchen Zeit — deine Zeit wird kommen.' }] },
    { word: '功亏一篑', pinyin: 'gōng kuī yī kuì', meaning: 'kurz vor dem Ziel scheitern', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '因为最后的粗心，他功亏一篑。', pinyin: 'Yīnwèi zuìhòu de cūxīn, tā gōng kuī yī kuì.', german: 'Wegen Unachtsamkeit in letzter Minute scheiterte er kurz vor dem Ziel.' }] },
    { word: '白手起家', pinyin: 'bái shǒu qǐ jiā', meaning: 'aus dem Nichts etwas aufbauen; sich hocharbeiten', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '他白手起家，从一个小店铺发展成了大企业。', pinyin: 'Tā bái shǒu qǐ jiā, cóng yī gè xiǎo diànpù fāzhǎn chéng le dà qǐyè.', german: 'Er hat aus dem Nichts angefangen und aus einem kleinen Laden ein grosses Unternehmen gemacht.' }] },

    // ========================
    // === GEFUEHLE ===
    // ========================

    { word: '心花怒放', pinyin: 'xīn huā nù fàng', meaning: 'uebergluecklich sein; vor Freude strahlen', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '听到被录取的消息，她心花怒放。', pinyin: 'Tīngdào bèi lùqǔ de xiāoxi, tā xīn huā nù fàng.', german: 'Als sie hoerte, dass sie angenommen wurde, strahlte sie vor Freude.' }] },
    { word: '心惊胆战', pinyin: 'xīn jīng dǎn zhàn', meaning: 'vor Angst zittern; entsetzt sein', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '看恐怖片看得心惊胆战。', pinyin: 'Kàn kǒngbù piàn kàn de xīn jīng dǎn zhàn.', german: 'Beim Horrorfilm hat man vor Angst gezittert.' }] },
    { word: '恋恋不舍', pinyin: 'liàn liàn bù shě', meaning: 'sich nur schwer trennen koennen; an etwas haengen', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '假期结束了，大家恋恋不舍地离开了海滩。', pinyin: 'Jiàqī jiéshù le, dàjiā liàn liàn bù shě de líkāi le hǎitān.', german: 'Der Urlaub war vorbei und alle verliessen nur ungern den Strand.' }] },
    { word: '喜出望外', pinyin: 'xǐ chū wàng wài', meaning: 'unerwartet erfreut; ueberraschend gluecklich', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '收到他的礼物，她喜出望外。', pinyin: 'Shōudào tā de lǐwù, tā xǐ chū wàng wài.', german: 'Als sie sein Geschenk erhielt, war sie unerwartet uebergluecklich.' }] },
    { word: '垂头丧气', pinyin: 'chuí tóu sàng qì', meaning: 'den Kopf haengen lassen; niedergeschlagen sein', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '考试没考好，他垂头丧气地走出教室。', pinyin: 'Kǎoshì méi kǎo hǎo, tā chuí tóu sàng qì de zǒuchū jiàoshì.', german: 'Weil die Pruefung schlecht lief, verliess er niedergeschlagen das Klassenzimmer.' }] },
    { word: '忐忑不安', pinyin: 'tǎn tè bù ān', meaning: 'unruhig und nervoes; ein mulmiges Gefuehl haben', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '面试前她忐忑不安，担心自己表现不好。', pinyin: 'Miànshì qián tā tǎn tè bù ān, dānxīn zìjǐ biǎoxiàn bù hǎo.', german: 'Vor dem Vorstellungsgespraech war sie nervoes und besorgt, nicht gut abzuschneiden.' }] },
    { word: '哭笑不得', pinyin: 'kū xiào bù dé', meaning: 'nicht wissen, ob man lachen oder weinen soll', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '孩子说的话常常让大人哭笑不得。', pinyin: 'Háizi shuō de huà chángcháng ràng dàrén kū xiào bù dé.', german: 'Was Kinder sagen, bringt Erwachsene oft dazu, nicht zu wissen, ob sie lachen oder weinen sollen.' }] },
    { word: '怒气冲冲', pinyin: 'nù qì chōng chōng', meaning: 'wutentbrannt; vor Wut schaeumend', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '他怒气冲冲地摔门而出。', pinyin: 'Tā nù qì chōng chōng de shuāi mén ér chū.', german: 'Er ging wutentbrannt hinaus und knallte die Tuer zu.' }] },
    { word: '心满意足', pinyin: 'xīn mǎn yì zú', meaning: 'vollkommen zufrieden und gluecklich', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '看到孩子们健康成长，她心满意足。', pinyin: 'Kàndào háizimen jiànkāng chéngzhǎng, tā xīn mǎn yì zú.', german: 'Zu sehen, wie die Kinder gesund aufwachsen, macht sie vollkommen zufrieden.' }] },
    { word: '触目伤心', pinyin: 'chù mù shāng xīn', meaning: 'ein trauriger Anblick; das Gesehene schmerzt das Herz', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '地震后的废墟令人触目伤心。', pinyin: 'Dìzhèn hòu de fèixū lìng rén chù mù shāng xīn.', german: 'Die Ruinen nach dem Erdbeben sind ein herzzerreissender Anblick.' }] },
    { word: '喜怒哀乐', pinyin: 'xǐ nù āi lè', meaning: 'Freude, Wut, Trauer und Glueck; alle Gefuehle', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '人生就是充满了喜怒哀乐。', pinyin: 'Rénshēng jiùshì chōngmǎn le xǐ nù āi lè.', german: 'Das Leben ist voller Freude, Wut, Trauer und Glueck.' }] },
    { word: '提心吊胆', pinyin: 'tí xīn diào dǎn', meaning: 'in staendiger Angst leben; auf heissen Kohlen sitzen', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '走夜路的时候提心吊胆的。', pinyin: 'Zǒu yèlù de shíhou tí xīn diào dǎn de.', german: 'Nachts allein unterwegs war man in staendiger Angst.' }] },
    { word: '刻骨铭心', pinyin: 'kè gǔ míng xīn', meaning: 'tief ins Herz eingeritzt; unvergesslich', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '这是一段刻骨铭心的经历。', pinyin: 'Zhè shì yī duàn kè gǔ míng xīn de jīnglì.', german: 'Das war ein unvergessliches Erlebnis.' }] },

    // ========================
    // === ARBEIT ===
    // ========================

    { word: '废寝忘食', pinyin: 'fèi qǐn wàng shí', meaning: 'Essen und Schlafen vergessen; voellig in der Arbeit aufgehen', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '为了完成项目，他废寝忘食地工作。', pinyin: 'Wèile wánchéng xiàngmù, tā fèi qǐn wàng shí de gōngzuò.', german: 'Um das Projekt abzuschliessen, hat er Tag und Nacht gearbeitet und alles andere vergessen.' }] },
    { word: '争分夺秒', pinyin: 'zhēng fēn duó miǎo', meaning: 'um jede Minute und Sekunde kaempfen; keine Zeit verschwenden', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '医生争分夺秒地抢救病人。', pinyin: 'Yīshēng zhēng fēn duó miǎo de qiǎngjiù bìngrén.', german: 'Die Aerzte kaempften um jede Sekunde, um den Patienten zu retten.' }] },
    { word: '精益求精', pinyin: 'jīng yì qiú jīng', meaning: 'nach Perfektion streben; staendig verbessern', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '德国工程师在技术上精益求精。', pinyin: 'Déguó gōngchéngshī zài jìshù shàng jīng yì qiú jīng.', german: 'Deutsche Ingenieure streben in der Technik stets nach Perfektion.' }] },
    { word: '一丝不苟', pinyin: 'yī sī bù gǒu', meaning: 'aeusserst gewissenhaft; bis ins kleinste Detail genau', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '他对工作一丝不苟，从不马虎。', pinyin: 'Tā duì gōngzuò yī sī bù gǒu, cóng bù mǎhu.', german: 'Er ist bei der Arbeit aeusserst gewissenhaft und nie schludrig.' }] },
    { word: '各司其职', pinyin: 'gè sī qí zhí', meaning: 'jeder erledigt seine Aufgabe; klare Aufgabenteilung', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '团队成员各司其职，项目进展顺利。', pinyin: 'Tuánduì chéngyuán gè sī qí zhí, xiàngmù jìnzhǎn shùnlì.', german: 'Jedes Teammitglied erledigt seine Aufgabe, das Projekt laeuft gut.' }] },
    { word: '全力以赴', pinyin: 'quán lì yǐ fù', meaning: 'mit aller Kraft; alles geben', type: 'Chengyu', level: 'HSK5', category: 'Arbeit', examples: [{ chinese: '为了赢得比赛，运动员们全力以赴。', pinyin: 'Wèile yíngdé bǐsài, yùndòngyuánmen quán lì yǐ fù.', german: 'Um das Spiel zu gewinnen, gaben die Sportler alles.' }] },
    { word: '齐心协力', pinyin: 'qí xīn xié lì', meaning: 'an einem Strang ziehen; gemeinsam anpacken', type: 'Chengyu', level: 'HSK5', category: 'Arbeit', examples: [{ chinese: '大家齐心协力，终于完成了任务。', pinyin: 'Dàjiā qí xīn xié lì, zhōngyú wánchéng le rènwu.', german: 'Alle zogen an einem Strang und vollendeten schliesslich die Aufgabe.' }] },
    { word: '事倍功半', pinyin: 'shì bèi gōng bàn', meaning: 'doppelter Aufwand, halber Erfolg; ineffizient arbeiten', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '没有好的计划就去做，往往事倍功半。', pinyin: 'Méiyǒu hǎo de jìhuà jiù qù zuò, wǎngwǎng shì bèi gōng bàn.', german: 'Ohne guten Plan loszulegen fuehrt oft zu doppeltem Aufwand bei halbem Ergebnis.' }] },
    { word: '力不从心', pinyin: 'lì bù cóng xīn', meaning: 'der Wille ist da, aber die Kraft fehlt', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '他年纪大了，干体力活有点力不从心。', pinyin: 'Tā niánjì dà le, gàn tǐlì huó yǒudiǎn lì bù cóng xīn.', german: 'Er ist aelter geworden und fuer koerperliche Arbeit fehlt ihm etwas die Kraft.' }] },
    { word: '手忙脚乱', pinyin: 'shǒu máng jiǎo luàn', meaning: 'in hektische Betriebsamkeit verfallen; kopflos handeln', type: 'Chengyu', level: 'HSK5', category: 'Arbeit', examples: [{ chinese: '客人突然来了，她手忙脚乱地准备。', pinyin: 'Kèren tūrán lái le, tā shǒu máng jiǎo luàn de zhǔnbèi.', german: 'Die Gaeste kamen ueberraschend und sie bereitete hektisch alles vor.' }] },
    { word: '日夜兼程', pinyin: 'rì yè jiān chéng', meaning: 'Tag und Nacht unterwegs sein; rastlos arbeiten', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '为了按时交货，工人们日夜兼程。', pinyin: 'Wèile ànshí jiāo huò, gōngrénmen rì yè jiān chéng.', german: 'Um puenktlich zu liefern, arbeiteten die Arbeiter Tag und Nacht.' }] },

    // ========================
    // === BEZIEHUNGEN ===
    // ========================

    { word: '对牛弹琴', pinyin: 'duì niú tán qín', meaning: 'vor tauben Ohren predigen; Perlen vor die Saeue werfen', type: 'Chengyu', level: 'HSK5', category: 'Beziehungen', examples: [{ chinese: '跟他讲道理简直是对牛弹琴。', pinyin: 'Gēn tā jiǎng dàolǐ jiǎnzhí shì duì niú tán qín.', german: 'Ihm Vernunft predigen zu wollen ist wie vor tauben Ohren zu reden.' }] },
    { word: '志同道合', pinyin: 'zhì tóng dào hé', meaning: 'gleiche Ziele und Ideale haben; gleichgesinnt', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们是志同道合的好朋友。', pinyin: 'Tāmen shì zhì tóng dào hé de hǎo péngyou.', german: 'Sie sind gleichgesinnte gute Freunde.' }] },
    { word: '情同手足', pinyin: 'qíng tóng shǒu zú', meaning: 'eng wie Geschwister; innige Freundschaft', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们两个情同手足，从小一起长大。', pinyin: 'Tāmen liǎng gè qíng tóng shǒu zú, cóng xiǎo yīqǐ zhǎngdà.', german: 'Die beiden sind eng wie Geschwister und zusammen aufgewachsen.' }] },
    { word: '一见如故', pinyin: 'yī jiàn rú gù', meaning: 'sich beim ersten Treffen wie alte Bekannte fuehlen', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们虽然是第一次见面，但一见如故。', pinyin: 'Tāmen suīrán shì dì yī cì jiànmiàn, dàn yī jiàn rú gù.', german: 'Obwohl sie sich zum ersten Mal trafen, fuehlten sie sich sofort wie alte Bekannte.' }] },
    { word: '同甘共苦', pinyin: 'tóng gān gòng kǔ', meaning: 'Freud und Leid gemeinsam teilen; durch dick und duenn', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '真正的朋友应该同甘共苦。', pinyin: 'Zhēnzhèng de péngyou yīnggāi tóng gān gòng kǔ.', german: 'Wahre Freunde sollten Freud und Leid gemeinsam teilen.' }] },
    { word: '患难之交', pinyin: 'huàn nàn zhī jiāo', meaning: 'Freund in der Not; Freundschaft, die in schweren Zeiten entstand', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们是患难之交，在最困难的时候互相帮助。', pinyin: 'Tāmen shì huàn nàn zhī jiāo, zài zuì kùnnan de shíhou hùxiāng bāngzhù.', german: 'Sie sind Freunde in der Not und haben sich in den schwersten Zeiten gegenseitig geholfen.' }] },
    { word: '相敬如宾', pinyin: 'xiāng jìng rú bīn', meaning: 'sich gegenseitig achten wie Gaeste; harmonische Ehe', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们夫妻相敬如宾，生活和谐。', pinyin: 'Tāmen fūqī xiāng jìng rú bīn, shēnghuó héxié.', german: 'Das Ehepaar achtet sich gegenseitig und lebt in Harmonie.' }] },
    { word: '青梅竹马', pinyin: 'qīng méi zhú mǎ', meaning: 'Kindheitsfreunde; zusammen aufgewachsen (oft: Sandkastenliebe)', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们是青梅竹马，从小就认识。', pinyin: 'Tāmen shì qīng méi zhú mǎ, cóng xiǎo jiù rènshi.', german: 'Sie sind Kindheitsfreunde und kennen sich schon von klein auf.' }] },
    { word: '两肋插刀', pinyin: 'liǎng lèi chā dāo', meaning: 'fuer jemanden durchs Feuer gehen; bedingungslos helfen', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '为了朋友，他愿意两肋插刀。', pinyin: 'Wèile péngyou, tā yuànyì liǎng lèi chā dāo.', german: 'Fuer seine Freunde wuerde er durchs Feuer gehen.' }] },
    { word: '形影不离', pinyin: 'xíng yǐng bù lí', meaning: 'unzertrennlich sein; wie Koerper und Schatten', type: 'Chengyu', level: 'HSK5', category: 'Beziehungen', examples: [{ chinese: '她们两个形影不离，到哪里都在一起。', pinyin: 'Tāmen liǎng gè xíng yǐng bù lí, dào nǎlǐ dōu zài yīqǐ.', german: 'Die beiden sind unzertrennlich und ueberall zusammen.' }] },
    { word: '相濡以沫', pinyin: 'xiāng rú yǐ mò', meaning: 'sich in der Not gegenseitig unterstuetzen (wie Fische, die sich gegenseitig befeuchten)', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们夫妻相濡以沫，共同度过了很多困难。', pinyin: 'Tāmen fūqī xiāng rú yǐ mò, gòngtóng dùguò le hěn duō kùnnan.', german: 'Das Ehepaar hat sich in der Not gegenseitig gestuetzt und viele Schwierigkeiten gemeinsam ueberstanden.' }] },

    // ========================
    // === LERNEN ===
    // ========================

    { word: '学以致用', pinyin: 'xué yǐ zhì yòng', meaning: 'das Gelernte in die Praxis umsetzen', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '学中文要学以致用，多跟中国人交流。', pinyin: 'Xué zhōngwén yào xué yǐ zhì yòng, duō gēn zhōngguó rén jiāoliú.', german: 'Beim Chinesischlernen muss man das Gelernte anwenden und viel mit Chinesen sprechen.' }] },
    { word: '举一反三', pinyin: 'jǔ yī fǎn sān', meaning: 'aus einem Beispiel drei Schlussfolgerungen ziehen; uebertragen koennen', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '好学生能举一反三，触类旁通。', pinyin: 'Hǎo xuéshēng néng jǔ yī fǎn sān, chù lèi páng tōng.', german: 'Gute Schueler koennen aus einem Beispiel Schlussfolgerungen ziehen und Zusammenhaenge erkennen.' }] },
    { word: '不耻下问', pinyin: 'bù chǐ xià wèn', meaning: 'sich nicht schaemen, Rangniedrigere zu fragen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '学习要不耻下问，不懂就要问。', pinyin: 'Xuéxí yào bù chǐ xià wèn, bù dǒng jiù yào wèn.', german: 'Beim Lernen soll man sich nicht schaemen zu fragen — wenn man etwas nicht versteht, muss man fragen.' }] },
    { word: '温故知新', pinyin: 'wēn gù zhī xīn', meaning: 'beim Wiederholen von Altem Neues entdecken', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '温故知新，每次复习都有新的收获。', pinyin: 'Wēn gù zhī xīn, měi cì fùxí dōu yǒu xīn de shōuhuò.', german: 'Beim Wiederholen entdeckt man Neues — jede Wiederholung bringt neue Erkenntnisse.' }] },
    { word: '融会贯通', pinyin: 'róng huì guàn tōng', meaning: 'alles zusammenfuegen und durchdringen; vollstaendig verstehen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '学了很多知识后，要融会贯通。', pinyin: 'Xué le hěn duō zhīshi hòu, yào róng huì guàn tōng.', german: 'Nachdem man viel gelernt hat, muss man alles zusammenfuegen und ganzheitlich verstehen.' }] },
    { word: '博览群书', pinyin: 'bó lǎn qún shū', meaning: 'umfassend belesen sein; viele Buecher lesen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '他从小博览群书，知识非常渊博。', pinyin: 'Tā cóng xiǎo bó lǎn qún shū, zhīshi fēicháng yuānbó.', german: 'Seit seiner Kindheit hat er viel gelesen und sein Wissen ist sehr umfassend.' }] },
    { word: '孜孜不倦', pinyin: 'zī zī bù juàn', meaning: 'unermüdlich lernen und arbeiten', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '他孜孜不倦地学习中文已经五年了。', pinyin: 'Tā zī zī bù juàn de xuéxí zhōngwén yǐjīng wǔ nián le.', german: 'Er lernt seit fuenf Jahren unermüdlich Chinesisch.' }] },
    { word: '学无止境', pinyin: 'xué wú zhǐ jìng', meaning: 'Lernen kennt keine Grenzen; man lernt nie aus', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '学无止境，活到老学到老。', pinyin: 'Xué wú zhǐ jìng, huó dào lǎo xué dào lǎo.', german: 'Lernen kennt keine Grenzen — man lernt ein Leben lang.' }] },
    { word: '囫囵吞枣', pinyin: 'hú lún tūn zǎo', meaning: 'eine Dattel im Ganzen verschlucken; ohne Verstaendnis auswendig lernen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '读书不能囫囵吞枣，要细细品味。', pinyin: 'Dúshū bù néng hú lún tūn zǎo, yào xìxì pǐnwèi.', german: 'Man darf nicht einfach Buecher verschlingen, sondern muss sie sorgfaeltig geniessen.' }] },
    { word: '勤能补拙', pinyin: 'qín néng bǔ zhuō', meaning: 'Fleiss kann Talent ersetzen; Uebung macht den Meister', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '他虽然天赋不高，但相信勤能补拙。', pinyin: 'Tā suīrán tiānfù bù gāo, dàn xiāngxìn qín néng bǔ zhuō.', german: 'Obwohl er kein grosses Talent hat, glaubt er, dass Fleiss es ausgleichen kann.' }] },
    { word: '如饥似渴', pinyin: 'rú jī sì kě', meaning: 'wie hungrig und durstig; wissbegierig; mit grossem Eifer', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '他如饥似渴地阅读各种书籍。', pinyin: 'Tā rú jī sì kě de yuèdú gè zhǒng shūjí.', german: 'Er liest mit grossem Wissensdurst alle moeglichen Buecher.' }] },

    // ========================
    // === GESCHICHTE ===
    // ========================

    { word: '刻舟求剑', pinyin: 'kè zhōu qiú jiàn', meaning: 'das Boot einritzen und dort das Schwert suchen; stur an Veraltetem festhalten', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '时代变了，不能刻舟求剑，要与时俱进。', pinyin: 'Shídài biàn le, bù néng kè zhōu qiú jiàn, yào yǔ shí jù jìn.', german: 'Die Zeiten haben sich geaendert, man darf nicht stur an Altem festhalten, sondern muss mit der Zeit gehen.' }] },
    { word: '守株待兔', pinyin: 'shǒu zhū dài tù', meaning: 'am Baumstumpf auf einen Hasen warten; auf einen Gluecksfall hoffen, statt zu handeln', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '不能守株待兔，要主动去寻找机会。', pinyin: 'Bù néng shǒu zhū dài tù, yào zhǔdòng qù xúnzhǎo jīhuì.', german: 'Man kann nicht tatenlos auf sein Glueck warten, sondern muss aktiv nach Moeglichkeiten suchen.' }] },
    { word: '画龙点睛', pinyin: 'huà lóng diǎn jīng', meaning: 'dem Drachen die Augen malen; das entscheidende Detail hinzufuegen', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '他在文章最后加了一句话，真是画龙点睛。', pinyin: 'Tā zài wénzhāng zuìhòu jiā le yī jù huà, zhēn shì huà lóng diǎn jīng.', german: 'Er fuegte am Ende des Artikels einen Satz hinzu — das war das Tuepfelchen auf dem i.' }] },
    { word: '井底之蛙', pinyin: 'jǐng dǐ zhī wā', meaning: 'Frosch im Brunnen; jemand mit begrenztem Horizont', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '不要做井底之蛙，要多出去看看世界。', pinyin: 'Bù yào zuò jǐng dǐ zhī wā, yào duō chūqù kànkan shìjiè.', german: 'Sei kein Frosch im Brunnen, geh raus und sieh dir die Welt an.' }] },
    { word: '狐假虎威', pinyin: 'hú jiǎ hǔ wēi', meaning: 'sich mit fremden Federn schmuecken; unter dem Deckmantel eines Maechtigeren drohen', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '他不过是狐假虎威，借老板的名义吓唬人。', pinyin: 'Tā bùguò shì hú jiǎ hǔ wēi, jiè lǎobǎn de míngyì xiàhu rén.', german: 'Er schmueckt sich nur mit fremden Federn und schuechert Leute im Namen des Chefs ein.' }] },
    { word: '掩耳盗铃', pinyin: 'yǎn ěr dào líng', meaning: 'sich die Ohren zuhalten und eine Glocke stehlen; sich selbst taeuschen', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '不面对现实就是掩耳盗铃。', pinyin: 'Bù miànduì xiànshí jiùshì yǎn ěr dào líng.', german: 'Die Realitaet nicht wahrhaben zu wollen ist Selbstbetrug.' }] },
    { word: '画蛇添足', pinyin: 'huà shé tiān zú', meaning: 'einer Schlange Fuesse malen; unnoetig uebertreiben; zu viel des Guten', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '你的报告已经很好了，不要画蛇添足。', pinyin: 'Nǐ de bàogào yǐjīng hěn hǎo le, bù yào huà shé tiān zú.', german: 'Dein Bericht ist schon sehr gut, uebertreib es nicht.' }] },
    { word: '拔苗助长', pinyin: 'bá miáo zhù zhǎng', meaning: 'die Setzlinge herausziehen, um ihnen beim Wachsen zu helfen; durch Ungeduld schaden', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '教育孩子不能拔苗助长，要有耐心。', pinyin: 'Jiàoyù háizi bù néng bá miáo zhù zhǎng, yào yǒu nàixīn.', german: 'Bei der Kindererziehung darf man nicht durch Ungeduld schaden, man braucht Geduld.' }] },
    { word: '望梅止渴', pinyin: 'wàng méi zhǐ kě', meaning: 'Pflaumen anschauen, um den Durst zu stillen; sich mit Illusionen troesten', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '光看菜单不吃，不过是望梅止渴。', pinyin: 'Guāng kàn càidān bù chī, bùguò shì wàng méi zhǐ kě.', german: 'Nur die Speisekarte anzuschauen ohne zu essen, ist wie sich mit Illusionen troesten.' }] },
    { word: '叶公好龙', pinyin: 'yè gōng hào lóng', meaning: 'wie Herr Ye, der Drachen liebte; etwas nur zum Schein moegen', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他说喜欢运动却从来不锻炼，真是叶公好龙。', pinyin: 'Tā shuō xǐhuan yùndòng què cónglái bù duànliàn, zhēn shì yè gōng hào lóng.', german: 'Er sagt, er mag Sport, trainiert aber nie — typischer Fall von: es nur zum Schein moegen.' }] },
    { word: '杯弓蛇影', pinyin: 'bēi gōng shé yǐng', meaning: 'den Bogenreflex im Becher fuer eine Schlange halten; grundlos Angst haben', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '别杯弓蛇影了，那只是树的影子。', pinyin: 'Bié bēi gōng shé yǐng le, nà zhǐ shì shù de yǐngzi.', german: 'Hab nicht grundlos Angst, das ist nur der Schatten eines Baumes.' }] },
    { word: '朝三暮四', pinyin: 'zhāo sān mù sì', meaning: 'wankelmuetig sein; unbestaendig; heute so, morgen so', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '做事不能朝三暮四，要有恒心。', pinyin: 'Zuòshì bù néng zhāo sān mù sì, yào yǒu héngxīn.', german: 'Man darf nicht wankelmuetig sein, man braucht Bestaendigkeit.' }] },
    { word: '打草惊蛇', pinyin: 'dǎ cǎo jīng shé', meaning: 'ins Gras schlagen und die Schlange aufschrecken; den Gegner unbeabsichtigt warnen', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '调查的时候要小心，别打草惊蛇。', pinyin: 'Diàochá de shíhou yào xiǎoxīn, bié dǎ cǎo jīng shé.', german: 'Bei der Untersuchung muss man vorsichtig sein und den Verdaechtigen nicht aufschrecken.' }] },
    { word: '卧薪尝胆', pinyin: 'wò xīn cháng dǎn', meaning: 'auf Reisig schlafen und Galle kosten; grosse Entbehrungen auf sich nehmen, um ein Ziel zu erreichen', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他卧薪尝胆十年，终于成功了。', pinyin: 'Tā wò xīn cháng dǎn shí nián, zhōngyú chénggōng le.', german: 'Er hat zehn Jahre lang grosse Entbehrungen auf sich genommen und schliesslich Erfolg gehabt.' }] },
    { word: '纸上谈兵', pinyin: 'zhǐ shàng tán bīng', meaning: 'auf dem Papier ueber Kriegsfuehrung reden; Theoretiker ohne Praxis', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '光纸上谈兵没有用，要实际行动。', pinyin: 'Guāng zhǐ shàng tán bīng méiyǒu yòng, yào shíjì xíngdòng.', german: 'Nur Theorie bringt nichts, man muss praktisch handeln.' }] },
    { word: '鹬蚌相争', pinyin: 'yù bàng xiāng zhēng', meaning: 'wenn Schnepfe und Muschel streiten, profitiert der Fischer; lachender Dritter', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '两家公司鹬蚌相争，第三家坐收渔利。', pinyin: 'Liǎng jiā gōngsī yù bàng xiāng zhēng, dì sān jiā zuò shōu yú lì.', german: 'Waehrend zwei Firmen sich stritten, strich die dritte den Gewinn ein.' }] },
    { word: '指鹿为马', pinyin: 'zhǐ lù wéi mǎ', meaning: 'auf einen Hirsch zeigen und behaupten, es sei ein Pferd; Schwarz fuer Weiss erklaeren', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '这种指鹿为马的做法是不对的。', pinyin: 'Zhè zhǒng zhǐ lù wéi mǎ de zuòfǎ shì bù duì de.', german: 'So die Wahrheit zu verdrehen ist falsch.' }] },
    { word: '破釜沉舟', pinyin: 'pò fǔ chén zhōu', meaning: 'die Kessel zerbrechen und die Boote versenken; alle Bruecken abbrechen und aufs Ganze gehen', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '这次比赛我们要破釜沉舟，全力以赴。', pinyin: 'Zhè cì bǐsài wǒmen yào pò fǔ chén zhōu, quán lì yǐ fù.', german: 'Bei diesem Wettkampf muessen wir alle Bruecken abbrechen und alles geben.' }] },
    { word: '完璧归赵', pinyin: 'wán bì guī zhào', meaning: 'die Jade unbeschaedigt nach Zhao zurueckbringen; etwas unversehrt zurueckgeben', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '这本书我看完了，现在完璧归赵。', pinyin: 'Zhè běn shū wǒ kàn wán le, xiànzài wán bì guī zhào.', german: 'Ich habe das Buch fertig gelesen und gebe es dir unversehrt zurueck.' }] },
    { word: '班门弄斧', pinyin: 'bān mén nòng fǔ', meaning: 'vor Lu Bans Tuer mit der Axt angeben; vor einem Fachmann aufschneiden', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '在语言学家面前谈语法，真是班门弄斧。', pinyin: 'Zài yǔyánxuéjiā miànqián tán yǔfǎ, zhēn shì bān mén nòng fǔ.', german: 'Vor einem Sprachwissenschaftler ueber Grammatik zu reden, das ist Eulen nach Athen tragen.' }] },
    { word: '愚公移山', pinyin: 'yú gōng yí shān', meaning: 'der alte Mann versetzt Berge; mit Ausdauer und Beharrlichkeit alles schaffen', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '我们要有愚公移山的精神，不怕困难。', pinyin: 'Wǒmen yào yǒu yú gōng yí shān de jīngshén, bù pà kùnnan.', german: 'Wir muessen den Geist haben, der Berge versetzt, und duerfen keine Schwierigkeiten fuerchten.' }] },

    // ========================
    // === WARNUNG ===
    // ========================

    { word: '不可思议', pinyin: 'bù kě sī yì', meaning: 'unvorstellbar; unfassbar; unglaublich', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '这件事太不可思议了，我简直不敢相信。', pinyin: 'Zhè jiàn shì tài bù kě sī yì le, wǒ jiǎnzhí bù gǎn xiāngxìn.', german: 'Das ist so unglaublich, ich kann es kaum fassen.' }] },
    { word: '鸡犬不宁', pinyin: 'jī quǎn bù níng', meaning: 'selbst Huehner und Hunde finden keine Ruhe; voelliges Chaos', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '邻居每天吵架，闹得鸡犬不宁。', pinyin: 'Línjū měi tiān chǎojià, nào de jī quǎn bù níng.', german: 'Die Nachbarn streiten jeden Tag und verursachen voelliges Chaos.' }] },
    { word: '得不偿失', pinyin: 'dé bù cháng shī', meaning: 'der Gewinn wiegt den Verlust nicht auf; es lohnt sich nicht', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '为了省一点钱而影响健康，真是得不偿失。', pinyin: 'Wèile shěng yīdiǎn qián ér yǐngxiǎng jiànkāng, zhēn shì dé bù cháng shī.', german: 'Fuer etwas Geld die Gesundheit zu ruinieren, das lohnt sich wirklich nicht.' }] },
    { word: '自食其果', pinyin: 'zì shí qí guǒ', meaning: 'die Fruechte des eigenen Handelns ernten; die Konsequenzen tragen', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '他不听劝告，现在自食其果。', pinyin: 'Tā bù tīng quàngào, xiànzài zì shí qí guǒ.', german: 'Er hat nicht auf den Rat gehoert und traegt jetzt die Konsequenzen.' }] },
    { word: '自作自受', pinyin: 'zì zuò zì shòu', meaning: 'selbst schuld; wer sich sein Bett macht, muss auch darin liegen', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '他自作自受，怨不得别人。', pinyin: 'Tā zì zuò zì shòu, yuàn bù de biéren.', german: 'Er ist selbst schuld, er kann niemandem anders die Schuld geben.' }] },
    { word: '玩火自焚', pinyin: 'wán huǒ zì fén', meaning: 'wer mit dem Feuer spielt, verbrennt sich', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '做违法的事就是玩火自焚。', pinyin: 'Zuò wéifǎ de shì jiùshì wán huǒ zì fén.', german: 'Wer Illegales tut, spielt mit dem Feuer und verbrennt sich.' }] },
    { word: '损人利己', pinyin: 'sǔn rén lì jǐ', meaning: 'anderen schaden, um sich selbst zu nuetzen; eigennuetzig', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '损人利己的行为不会有好结果。', pinyin: 'Sǔn rén lì jǐ de xíngwéi bù huì yǒu hǎo jiéguǒ.', german: 'Eigennuetziges Verhalten auf Kosten anderer wird kein gutes Ende nehmen.' }] },
    { word: '贪小便宜吃大亏', pinyin: 'tān xiǎo piányi chī dà kuī', meaning: 'wer auf kleine Vorteile aus ist, erleidet grossen Schaden', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '买假冒产品就是贪小便宜吃大亏。', pinyin: 'Mǎi jiǎmào chǎnpǐn jiùshì tān xiǎo piányi chī dà kuī.', german: 'Faelschungen zu kaufen ist ein typischer Fall von: am falschen Ende sparen.' }] },
    { word: '异想天开', pinyin: 'yì xiǎng tiān kāi', meaning: 'voellig unrealistische Vorstellungen haben; Hirngespinste', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '你想一个月学会中文？别异想天开了！', pinyin: 'Nǐ xiǎng yī gè yuè xuéhuì zhōngwén? Bié yì xiǎng tiān kāi le!', german: 'Du willst in einem Monat Chinesisch lernen? Hoer auf zu traeumen!' }] },
    { word: '自相矛盾', pinyin: 'zì xiāng máo dùn', meaning: 'sich selbst widersprechen; widersprüchlich', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '他的话前后自相矛盾，不可信。', pinyin: 'Tā de huà qiánhòu zì xiāng máo dùn, bù kě xìn.', german: 'Seine Aussagen widersprechen sich und sind nicht glaubwuerdig.' }] },
    { word: '走马观花', pinyin: 'zǒu mǎ guān huā', meaning: 'vom Pferd aus Blumen betrachten; nur oberflaechlich betrachten', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '旅游不能走马观花，要深入了解当地文化。', pinyin: 'Lǚyóu bù néng zǒu mǎ guān huā, yào shēnrù liǎojiě dāngdì wénhuà.', german: 'Beim Reisen darf man nicht alles nur oberflaechlich betrachten, man sollte die lokale Kultur wirklich kennenlernen.' }] },
    { word: '好高骛远', pinyin: 'hào gāo wù yuǎn', meaning: 'nach Hoeherem streben, als man erreichen kann; unrealistische Ziele setzen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '做事不能好高骛远，要一步一步来。', pinyin: 'Zuòshì bù néng hào gāo wù yuǎn, yào yī bù yī bù lái.', german: 'Man darf sich keine unrealistischen Ziele setzen, sondern muss Schritt fuer Schritt vorgehen.' }] },
    { word: '画饼充饥', pinyin: 'huà bǐng chōng jī', meaning: 'einen Kuchen malen, um den Hunger zu stillen; leere Versprechungen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '老板只会画饼充饥，从来不兑现承诺。', pinyin: 'Lǎobǎn zhǐ huì huà bǐng chōng jī, cónglái bù duìxiàn chéngnuò.', german: 'Der Chef macht nur leere Versprechungen und haelt sie nie ein.' }] },
    { word: '盲人摸象', pinyin: 'máng rén mō xiàng', meaning: 'Blinde tasten einen Elefanten ab; voreilige Schlussfolgerungen aus begrenzter Sicht', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '只看局部就下结论，那是盲人摸象。', pinyin: 'Zhǐ kàn júbù jiù xià jiélùn, nà shì máng rén mō xiàng.', german: 'Nur einen Teil zu sehen und daraus Schluesse zu ziehen, das ist wie wenn Blinde einen Elefanten ertasten.' }] },
    { word: '弄巧成拙', pinyin: 'nòng qiǎo chéng zhuō', meaning: 'sich mit Geschick selbst schaden; der Schuss geht nach hinten los', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '他想讨好上司，结果弄巧成拙。', pinyin: 'Tā xiǎng tǎohǎo shàngsī, jiéguǒ nòng qiǎo chéng zhuō.', german: 'Er wollte sich beim Chef einschmeicheln, aber der Schuss ging nach hinten los.' }] },
    { word: '坐井观天', pinyin: 'zuò jǐng guān tiān', meaning: 'vom Brunnen aus den Himmel betrachten; beschraenkte Weltsicht', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '不要坐井观天，要多出去看看。', pinyin: 'Bù yào zuò jǐng guān tiān, yào duō chūqù kànkan.', german: 'Bleib nicht in deinem engen Horizont, geh raus und erweitere deinen Blick.' }] },
    { word: '杞人忧天', pinyin: 'qǐ rén yōu tiān', meaning: 'sich unnoetige Sorgen machen; Angst haben, der Himmel koennte einstuerzen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '别杞人忧天了，事情没有那么严重。', pinyin: 'Bié qǐ rén yōu tiān le, shìqíng méiyǒu nàme yánzhòng.', german: 'Mach dir keine unnuetigen Sorgen, es ist nicht so schlimm.' }] },
    { word: '以貌取人', pinyin: 'yǐ mào qǔ rén', meaning: 'Menschen nach dem Aeusseren beurteilen', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '不能以貌取人，要看内在。', pinyin: 'Bù néng yǐ mào qǔ rén, yào kàn nèizài.', german: 'Man darf Menschen nicht nach dem Aeusseren beurteilen, man muss auf das Innere schauen.' }] },
    { word: '舍本逐末', pinyin: 'shě běn zhú mò', meaning: 'das Wesentliche aufgeben und dem Nebensaechlichen nachjagen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '只追求外表而忽视品质，是舍本逐末。', pinyin: 'Zhǐ zhuīqiú wàibiǎo ér hūshì pǐnzhì, shì shě běn zhú mò.', german: 'Nur auf das Aeussere zu achten und die Qualitaet zu vernachlaessigen, heisst das Wesentliche aufzugeben.' }] },
    { word: '此地无银三百两', pinyin: 'cǐ dì wú yín sān bǎi liǎng', meaning: 'hier sind keine dreihundert Tael Silber vergraben; sich durch Leugnen verdaechtig machen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '他越解释，越像此地无银三百两。', pinyin: 'Tā yuè jiěshì, yuè xiàng cǐ dì wú yín sān bǎi liǎng.', german: 'Je mehr er sich erklaert, desto verdaechtiger macht er sich.' }] },

    // ========================
    // === WEITERE LEBENSWEISHEITEN ===
    // ========================

    { word: '百闻不如一见', pinyin: 'bǎi wén bù rú yī jiàn', meaning: 'einmal sehen ist besser als hundertmal hoeren', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '中国的长城百闻不如一见，真的很壮观。', pinyin: 'Zhōngguó de chángchéng bǎi wén bù rú yī jiàn, zhēn de hěn zhuàngguān.', german: 'Die Grosse Mauer muss man mit eigenen Augen sehen, sie ist wirklich beeindruckend.' }] },
    { word: '熟能生巧', pinyin: 'shú néng shēng qiǎo', meaning: 'Uebung macht den Meister', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '写汉字只要多练习，熟能生巧。', pinyin: 'Xiě hànzì zhǐyào duō liànxí, shú néng shēng qiǎo.', german: 'Chinesische Schriftzeichen zu schreiben erfordert nur viel Uebung — Uebung macht den Meister.' }] },
    { word: '欲速则不达', pinyin: 'yù sù zé bù dá', meaning: 'Eile mit Weile; wer zu schnell will, kommt nicht an', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '学语言要有耐心，欲速则不达。', pinyin: 'Xué yǔyán yào yǒu nàixīn, yù sù zé bù dá.', german: 'Beim Sprachenlernen braucht man Geduld — Eile mit Weile.' }] },
    { word: '有志者事竟成', pinyin: 'yǒu zhì zhě shì jìng chéng', meaning: 'wo ein Wille ist, ist auch ein Weg', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '只要你不放弃，有志者事竟成。', pinyin: 'Zhǐyào nǐ bù fàngqì, yǒu zhì zhě shì jìng chéng.', german: 'Solange du nicht aufgibst, ist da, wo ein Wille ist, auch ein Weg.' }] },
    { word: '吃一堑长一智', pinyin: 'chī yī qiàn zhǎng yī zhì', meaning: 'aus Fehlern lernt man; durch einen Fehler wird man klueger', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '这次失败不要紧，吃一堑长一智嘛。', pinyin: 'Zhè cì shībài bù yàojǐn, chī yī qiàn zhǎng yī zhì ma.', german: 'Diese Niederlage ist nicht schlimm — aus Fehlern lernt man.' }] },
    { word: '当局者迷', pinyin: 'dāng jú zhě mí', meaning: 'wer mitten drin steckt, sieht den Wald vor lauter Baeumen nicht', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '当局者迷，旁观者清，你让别人帮你分析一下。', pinyin: 'Dāng jú zhě mí, pángguān zhě qīng, nǐ ràng biéren bāng nǐ fēnxī yīxià.', german: 'Wer mitten drin steckt, sieht es nicht klar — lass dir von anderen helfen, die Lage zu analysieren.' }] },

    // ========================
    // === WEITERE CHARAKTER ===
    // ========================

    { word: '不卑不亢', pinyin: 'bù bēi bù kàng', meaning: 'weder unterwuerfig noch ueberheblich; selbstsicher auftreten', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '她对待客户总是不卑不亢，很有分寸。', pinyin: 'Tā duìdài kèhù zǒng shì bù bēi bù kàng, hěn yǒu fēncùn.', german: 'Im Umgang mit Kunden tritt sie stets weder unterwuerfig noch ueberheblich auf, mit grossem Fingerspitzengefuehl.' }] },
    { word: '乐此不疲', pinyin: 'lè cǐ bù pí', meaning: 'mit unermüdlicher Freude etwas tun; sich nie daran satt sehen', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他对收集邮票乐此不疲。', pinyin: 'Tā duì shōují yóupiào lè cǐ bù pí.', german: 'Er sammelt mit unermüdlicher Freude Briefmarken.' }] },
    { word: '言行一致', pinyin: 'yán xíng yī zhì', meaning: 'Worte und Taten stimmen ueberein; zu seinem Wort stehen', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '做人要言行一致，不能说一套做一套。', pinyin: 'Zuòrén yào yán xíng yī zhì, bù néng shuō yī tào zuò yī tào.', german: 'Man muss zu seinem Wort stehen und darf nicht eins sagen und etwas anderes tun.' }] },
    { word: '表里如一', pinyin: 'biǎo lǐ rú yī', meaning: 'aussen und innen sind gleich; aufrichtig und ehrlich', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他是个表里如一的人，从不虚伪。', pinyin: 'Tā shì gè biǎo lǐ rú yī de rén, cóng bù xūwěi.', german: 'Er ist ein aufrichtiger Mensch und nie heuchlerisch.' }] },
    { word: '安分守己', pinyin: 'ān fèn shǒu jǐ', meaning: 'brav und pflichtbewusst; sich an Regeln halten', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他一直安分守己，从不惹是生非。', pinyin: 'Tā yīzhí ān fèn shǒu jǐ, cóng bù rě shì shēng fēi.', german: 'Er ist stets pflichtbewusst und sucht nie Streit.' }] },

    // ========================
    // === WEITERE NATUR ===
    // ========================

    { word: '风吹草动', pinyin: 'fēng chuī cǎo dòng', meaning: 'wenn der Wind weht, bewegt sich das Gras; kleinste Anzeichen von Unruhe', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '他很敏感，有一点风吹草动就紧张。', pinyin: 'Tā hěn mǐngǎn, yǒu yīdiǎn fēng chuī cǎo dòng jiù jǐnzhāng.', german: 'Er ist sehr empfindlich und wird bei der kleinsten Unruhe nervoes.' }] },
    { word: '雪中送炭', pinyin: 'xuě zhōng sòng tàn', meaning: 'im Schnee Kohlen schicken; in der Not helfen', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '他在我最困难的时候帮助了我，真是雪中送炭。', pinyin: 'Tā zài wǒ zuì kùnnan de shíhou bāngzhù le wǒ, zhēn shì xuě zhōng sòng tàn.', german: 'Er hat mir in meiner groessten Not geholfen — das war wirklich Hilfe in der Not.' }] },
    { word: '锦上添花', pinyin: 'jǐn shàng tiān huā', meaning: 'Blumen auf Brokat sticken; etwas Gutes noch besser machen', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '在好的基础上再改进，就是锦上添花。', pinyin: 'Zài hǎo de jīchǔ shàng zài gǎijìn, jiùshì jǐn shàng tiān huā.', german: 'Auf einer guten Grundlage noch zu verbessern, das ist das Tuepfelchen auf dem i.' }] },
    { word: '望洋兴叹', pinyin: 'wàng yáng xīng tàn', meaning: 'aufs Meer schauen und seufzen; vor einer uebermaechtigen Aufgabe stehen', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '面对这么复杂的问题，我只能望洋兴叹。', pinyin: 'Miànduì zhème fùzá de wèntí, wǒ zhǐ néng wàng yáng xīng tàn.', german: 'Angesichts dieses so komplizierten Problems kann ich nur seufzend aufgeben.' }] },
    { word: '落花流水', pinyin: 'luò huā liú shuǐ', meaning: 'fallende Blumen und fliessendes Wasser; eine vernichtende Niederlage', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '对手被打得落花流水。', pinyin: 'Duìshǒu bèi dǎ de luò huā liú shuǐ.', german: 'Der Gegner wurde vernichtend geschlagen.' }] },

    // ========================
    // === WEITERE ERFOLG ===
    // ========================

    { word: '旗开得胜', pinyin: 'qí kāi dé shèng', meaning: 'von Anfang an siegen; einen guten Start haben', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '祝你们旗开得胜！', pinyin: 'Zhù nǐmen qí kāi dé shèng!', german: 'Ich wuensche euch einen guten Start und Erfolg von Anfang an!' }] },
    { word: '势不可挡', pinyin: 'shì bù kě dǎng', meaning: 'unaufhaltsam; nicht aufzuhalten', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '这家公司的发展势不可挡。', pinyin: 'Zhè jiā gōngsī de fāzhǎn shì bù kě dǎng.', german: 'Die Entwicklung dieses Unternehmens ist nicht aufzuhalten.' }] },
    { word: '后来居上', pinyin: 'hòu lái jū shàng', meaning: 'der Spaetere ueberholt die Frueheren; von hinten aufrücken', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '他虽然起步晚，但后来居上，超过了所有人。', pinyin: 'Tā suīrán qǐbù wǎn, dàn hòu lái jū shàng, chāoguò le suǒyǒu rén.', german: 'Obwohl er spaet angefangen hat, hat er von hinten aufgeholt und alle ueberholt.' }] },
    { word: '一鸣惊人', pinyin: 'yī míng jīng rén', meaning: 'mit einem Schlag alle ueberraschen; ploetzlich glaenzen', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '他平时不起眼，比赛中却一鸣惊人。', pinyin: 'Tā píngshí bù qǐyǎn, bǐsài zhōng què yī míng jīng rén.', german: 'Im Alltag faellt er nicht auf, aber im Wettkampf ueberraschte er alle.' }] },
    { word: '独占鳌头', pinyin: 'dú zhàn áo tóu', meaning: 'den ersten Platz belegen; die Spitze einnehmen', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '他在这次考试中独占鳌头。', pinyin: 'Tā zài zhè cì kǎoshì zhōng dú zhàn áo tóu.', german: 'Er hat bei dieser Pruefung den ersten Platz belegt.' }] },

    // ========================
    // === WEITERE GEFUEHLE ===
    // ========================

    { word: '兴高采烈', pinyin: 'xìng gāo cǎi liè', meaning: 'ueberaus froh und begeistert; in Hochstimmung', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '孩子们兴高采烈地去游乐园。', pinyin: 'Háizimen xìng gāo cǎi liè de qù yóulèyuán.', german: 'Die Kinder gingen ueberaus begeistert in den Vergnuegungspark.' }] },
    { word: '心不在焉', pinyin: 'xīn bù zài yān', meaning: 'geistesabwesend; unaufmerksam; mit den Gedanken woanders', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '他上课心不在焉，一直在想别的事。', pinyin: 'Tā shàngkè xīn bù zài yān, yīzhí zài xiǎng bié de shì.', german: 'Im Unterricht war er geistesabwesend und dachte staendig an andere Dinge.' }] },
    { word: '心急如焚', pinyin: 'xīn jí rú fén', meaning: 'vor Ungeduld brennen; aeusserst besorgt sein', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '孩子没回来，妈妈心急如焚。', pinyin: 'Háizi méi huílái, māma xīn jí rú fén.', german: 'Das Kind kam nicht nach Hause und die Mutter war vor Sorge ganz ausser sich.' }] },
    { word: '乐不思蜀', pinyin: 'lè bù sī shǔ', meaning: 'so gluecklich sein, dass man die Heimat vergisst; sich pudelwohl fuehlen', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '他在德国生活得乐不思蜀。', pinyin: 'Tā zài déguó shēnghuó de lè bù sī shǔ.', german: 'Er fuehlt sich in Deutschland so wohl, dass er die Heimat vergisst.' }] },
    { word: '泪流满面', pinyin: 'lèi liú mǎn miàn', meaning: 'Traenen laufen uebers ganze Gesicht; in Traenen aufgeloest', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '看完那部电影，她泪流满面。', pinyin: 'Kàn wán nà bù diànyǐng, tā lèi liú mǎn miàn.', german: 'Nach dem Film war sie in Traenen aufgeloest.' }] },
    { word: '悲喜交加', pinyin: 'bēi xǐ jiāo jiā', meaning: 'Freude und Trauer zugleich; gemischte Gefuehle', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '听到这个消息，她悲喜交加。', pinyin: 'Tīngdào zhège xiāoxi, tā bēi xǐ jiāo jiā.', german: 'Als sie die Nachricht hoerte, hatte sie gemischte Gefuehle.' }] },
    { word: '痛不欲生', pinyin: 'tòng bù yù shēng', meaning: 'so schmerzerfuellt, dass man nicht mehr leben moechte; untroestlich', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '失去亲人让他痛不欲生。', pinyin: 'Shīqù qīnrén ràng tā tòng bù yù shēng.', german: 'Der Verlust seiner Angehoerigen machte ihn untroestlich.' }] },

    // ========================
    // === WEITERE ARBEIT ===
    // ========================

    { word: '得心应手', pinyin: 'dé xīn yìng shǒu', meaning: 'etwas muehelos beherrschen; in Fleisch und Blut uebergegangen', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '多年的经验让他工作起来得心应手。', pinyin: 'Duō nián de jīngyàn ràng tā gōngzuò qǐlái dé xīn yìng shǒu.', german: 'Durch seine langjährige Erfahrung beherrscht er seine Arbeit muehelos.' }] },
    { word: '独当一面', pinyin: 'dú dāng yī miàn', meaning: 'ein Aufgabengebiet eigenstaendig leiten; auf eigenen Beinen stehen', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '他已经能独当一面了，不需要别人帮忙。', pinyin: 'Tā yǐjīng néng dú dāng yī miàn le, bù xūyào biéren bāngmáng.', german: 'Er kann inzwischen selbstaendig arbeiten und braucht keine Hilfe mehr.' }] },
    { word: '有条不紊', pinyin: 'yǒu tiáo bù wěn', meaning: 'geordnet und systematisch; wohlorganisiert', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '她把工作安排得有条不紊。', pinyin: 'Tā bǎ gōngzuò ānpái de yǒu tiáo bù wěn.', german: 'Sie hat die Arbeit wohlorganisiert eingeteilt.' }] },
    { word: '分工合作', pinyin: 'fēn gōng hé zuò', meaning: 'Arbeitsteilung und Zusammenarbeit', type: 'Chengyu', level: 'HSK5', category: 'Arbeit', examples: [{ chinese: '大家分工合作，效率很高。', pinyin: 'Dàjiā fēn gōng hé zuò, xiàolǜ hěn gāo.', german: 'Alle teilen sich die Arbeit auf und arbeiten zusammen — die Effizienz ist hoch.' }] },
    { word: '游刃有余', pinyin: 'yóu rèn yǒu yú', meaning: 'das Messer gleitet muehelos; etwas mit Leichtigkeit meistern', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '对于这种工作，他早已游刃有余。', pinyin: 'Duìyú zhè zhǒng gōngzuò, tā zǎo yǐ yóu rèn yǒu yú.', german: 'Diese Art von Arbeit meistert er laengst mit Leichtigkeit.' }] },

    // ========================
    // === WEITERE BEZIEHUNGEN ===
    // ========================

    { word: '心心相印', pinyin: 'xīn xīn xiāng yìn', meaning: 'Herzen, die fuereinander schlagen; sich ohne Worte verstehen', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们是心心相印的好搭档。', pinyin: 'Tāmen shì xīn xīn xiāng yìn de hǎo dādàng.', german: 'Sie sind ein perfektes Team, das sich ohne Worte versteht.' }] },
    { word: '背道而驰', pinyin: 'bèi dào ér chí', meaning: 'in die entgegengesetzte Richtung laufen; voellig entgegengesetzt', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他的做法与我们的目标背道而驰。', pinyin: 'Tā de zuòfǎ yǔ wǒmen de mùbiāo bèi dào ér chí.', german: 'Sein Vorgehen laeuft unserem Ziel voellig entgegen.' }] },
    { word: '推心置腹', pinyin: 'tuī xīn zhì fù', meaning: 'offen und ehrlich miteinander reden; sein Herz ausschuetten', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们推心置腹地谈了一个晚上。', pinyin: 'Tāmen tuī xīn zhì fù de tán le yī gè wǎnshàng.', german: 'Sie haben sich einen ganzen Abend lang offen und ehrlich ausgesprochen.' }] },
    { word: '素不相识', pinyin: 'sù bù xiāng shí', meaning: 'sich ueberhaupt nicht kennen; voellig fremd', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他们素不相识，却像老朋友一样聊了起来。', pinyin: 'Tāmen sù bù xiāng shí, què xiàng lǎo péngyou yīyàng liáo le qǐlái.', german: 'Sie kannten sich ueberhaupt nicht, plauderten aber los wie alte Freunde.' }] },

    // ========================
    // === WEITERE LERNEN ===
    // ========================

    { word: '触类旁通', pinyin: 'chù lèi páng tōng', meaning: 'von einem Fall auf aehnliche schliessen; Zusammenhaenge erkennen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '学会一种编程语言，就能触类旁通，学其他的更容易。', pinyin: 'Xuéhuì yī zhǒng biānchéng yǔyán, jiù néng chù lèi páng tōng, xué qítā de gèng róngyì.', german: 'Wenn man eine Programmiersprache gelernt hat, erkennt man Zusammenhaenge und lernt andere leichter.' }] },
    { word: '不懂装懂', pinyin: 'bù dǒng zhuāng dǒng', meaning: 'so tun, als ob man etwas versteht; Unwissenheit verbergen', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '学习的时候不要不懂装懂，要老实请教。', pinyin: 'Xuéxí de shíhou bù yào bù dǒng zhuāng dǒng, yào lǎoshí qǐngjiào.', german: 'Beim Lernen soll man nicht so tun, als verstuende man alles, sondern ehrlich nachfragen.' }] },
    { word: '见多识广', pinyin: 'jiàn duō shí guǎng', meaning: 'viel gesehen und erfahren haben; weitgereist und belesen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '她去过很多国家，见多识广。', pinyin: 'Tā qù guò hěn duō guójiā, jiàn duō shí guǎng.', german: 'Sie hat viele Laender besucht und ist sehr erfahren.' }] },
    { word: '死记硬背', pinyin: 'sǐ jì yìng bèi', meaning: 'stumpf auswendig lernen; pauken ohne Verstaendnis', type: 'Chengyu', level: 'HSK5', category: 'Lernen', examples: [{ chinese: '学语言不能死记硬背，要在实际中运用。', pinyin: 'Xué yǔyán bù néng sǐ jì yìng bèi, yào zài shíjì zhōng yùnyòng.', german: 'Sprachen lernen geht nicht durch stumpfes Auswendiglernen, man muss sie praktisch anwenden.' }] },
    { word: '循序渐进', pinyin: 'xún xù jiàn jìn', meaning: 'Schritt fuer Schritt vorgehen; systematisch lernen', type: 'Chengyu', level: 'HSK6', category: 'Lernen', examples: [{ chinese: '学习中文要循序渐进，不能急于求成。', pinyin: 'Xuéxí zhōngwén yào xún xù jiàn jìn, bù néng jí yú qiú chéng.', german: 'Chinesisch muss man Schritt fuer Schritt lernen und darf es nicht ueberhasten.' }] },

    // ========================
    // === WEITERE GESCHICHTE ===
    // ========================

    { word: '四面楚歌', pinyin: 'sì miàn chǔ gē', meaning: 'von allen Seiten Chu-Lieder hoeren; voellig umzingelt und isoliert', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '公司面临四面楚歌的困境。', pinyin: 'Gōngsī miànlín sì miàn chǔ gē de kùnjìng.', german: 'Das Unternehmen befindet sich in einer Lage, in der es von allen Seiten unter Druck steht.' }] },
    { word: '三顾茅庐', pinyin: 'sān gù máo lú', meaning: 'dreimal die strohgedeckte Huette besuchen; jemanden beharrlich um Hilfe bitten', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '老板三顾茅庐，终于请到了这位专家。', pinyin: 'Lǎobǎn sān gù máo lú, zhōngyú qǐng dào le zhè wèi zhuānjiā.', german: 'Der Chef bemühte sich beharrlich und konnte den Experten schliesslich gewinnen.' }] },
    { word: '负荆请罪', pinyin: 'fù jīng qǐng zuì', meaning: 'mit Dornen auf dem Ruecken um Verzeihung bitten; reumuetig um Entschuldigung bitten', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他意识到自己的错误后，负荆请罪。', pinyin: 'Tā yìshí dào zìjǐ de cuòwù hòu, fù jīng qǐng zuì.', german: 'Nachdem er seinen Fehler erkannt hatte, bat er reumuetig um Verzeihung.' }] },
    { word: '东施效颦', pinyin: 'dōng shī xiào pín', meaning: 'die haessliche Dong Shi ahmt die schoene Xi Shi nach; unbeholfene Nachahmung', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '不要东施效颦，要找到自己的风格。', pinyin: 'Bù yào dōng shī xiào pín, yào zhǎodào zìjǐ de fēnggé.', german: 'Ahme nicht unbeholfen andere nach, finde deinen eigenen Stil.' }] },
    { word: '对症下药', pinyin: 'duì zhèng xià yào', meaning: 'die Medizin auf die Krankheit abstimmen; gezielte Massnahmen ergreifen', type: 'Chengyu', level: 'HSK5', category: 'Geschichte', examples: [{ chinese: '解决问题要对症下药，不能盲目。', pinyin: 'Jiějué wèntí yào duì zhèng xià yào, bù néng mángmù.', german: 'Beim Problemloesen muss man gezielt vorgehen und darf nicht blind handeln.' }] },

    // ========================
    // === WEITERE WARNUNG ===
    // ========================

    { word: '本末倒置', pinyin: 'běn mò dào zhì', meaning: 'Haupt- und Nebensache verwechseln; die Prioritaeten falsch setzen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '只注重成绩而忽视健康，是本末倒置。', pinyin: 'Zhǐ zhùzhòng chéngjì ér hūshì jiànkāng, shì běn mò dào zhì.', german: 'Nur auf Noten zu achten und die Gesundheit zu vernachlaessigen, heisst die Prioritaeten falsch zu setzen.' }] },
    { word: '急功近利', pinyin: 'jí gōng jìn lì', meaning: 'auf schnellen Erfolg und sofortigen Gewinn aus sein; kurzfristig denken', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '做学问不能急功近利，要有长远的眼光。', pinyin: 'Zuò xuéwèn bù néng jí gōng jìn lì, yào yǒu chángyuǎn de yǎnguāng.', german: 'In der Wissenschaft darf man nicht kurzfristig denken, man braucht einen langfristigen Blick.' }] },
    { word: '鱼目混珠', pinyin: 'yú mù hùn zhū', meaning: 'Fischaugen fuer Perlen ausgeben; Faelschungen unterschieben', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '市场上有些商品鱼目混珠，消费者要小心。', pinyin: 'Shìchǎng shàng yǒuxiē shāngpǐn yú mù hùn zhū, xiāofèizhě yào xiǎoxīn.', german: 'Auf dem Markt werden manchmal Faelschungen untergeschoben, Verbraucher muessen aufpassen.' }] },
    { word: '一意孤行', pinyin: 'yī yì gū xíng', meaning: 'eigensinnig seinen Weg gehen; unbeirrt auf dem eigenen Standpunkt beharren', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '他一意孤行，不听任何人的劝告。', pinyin: 'Tā yī yì gū xíng, bù tīng rènhé rén de quàngào.', german: 'Er geht eigensinnig seinen Weg und hoert auf niemandes Rat.' }] },
    { word: '饮鸩止渴', pinyin: 'yǐn zhèn zhǐ kě', meaning: 'Gift trinken, um den Durst zu loeschen; kurzfristige Loesung mit langfristigem Schaden', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '借高利贷还债不过是饮鸩止渴。', pinyin: 'Jiè gāolìdài huánzhài bùguò shì yǐn zhèn zhǐ kě.', german: 'Wucherkredite aufzunehmen, um Schulden zu bezahlen, ist wie Gift gegen den Durst zu trinken.' }] },

    // ========================
    // === ZUSAETZLICHE MISCHUNG ===
    // ========================

    { word: '如虎添翼', pinyin: 'rú hǔ tiān yì', meaning: 'wie ein Tiger mit Fluegeln; noch maechtigere Unterstuetzung bekommen', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '有了新技术的支持，公司如虎添翼。', pinyin: 'Yǒu le xīn jìshù de zhīchí, gōngsī rú hǔ tiān yì.', german: 'Mit der Unterstuetzung neuer Technologie wurde das Unternehmen noch staerker.' }] },
    { word: '不翼而飞', pinyin: 'bù yì ér fēi', meaning: 'ohne Fluegel davonfliegen; spurlos verschwinden', type: 'Chengyu', level: 'HSK5', category: 'Warnung', examples: [{ chinese: '我的钱包不翼而飞了！', pinyin: 'Wǒ de qiánbāo bù yì ér fēi le!', german: 'Meine Geldboerse ist spurlos verschwunden!' }] },
    { word: '与时俱进', pinyin: 'yǔ shí jù jìn', meaning: 'mit der Zeit gehen; sich weiterentwickeln', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '我们要与时俱进，不断学习新知识。', pinyin: 'Wǒmen yào yǔ shí jù jìn, bùduàn xuéxí xīn zhīshi.', german: 'Wir muessen mit der Zeit gehen und staendig neues Wissen erwerben.' }] },
    { word: '无中生有', pinyin: 'wú zhōng shēng yǒu', meaning: 'aus dem Nichts etwas erschaffen; etwas erfinden/erlügen', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '这些谣言都是无中生有的。', pinyin: 'Zhèxiē yáoyán dōu shì wú zhōng shēng yǒu de.', german: 'Diese Geruechte sind alle frei erfunden.' }] },
    { word: '目瞪口呆', pinyin: 'mù dèng kǒu dāi', meaning: 'Augen und Mund weit aufreissen; sprachlos und erstaunt sein', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '听到这个消息，他目瞪口呆。', pinyin: 'Tīngdào zhège xiāoxi, tā mù dèng kǒu dāi.', german: 'Als er die Nachricht hoerte, war er sprachlos vor Erstaunen.' }] },
    { word: '天衣无缝', pinyin: 'tiān yī wú fèng', meaning: 'nahtlos wie ein himmlisches Gewand; makellos und lueckenlos', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '这个计划天衣无缝，不会出问题。', pinyin: 'Zhège jìhuà tiān yī wú fèng, bù huì chū wèntí.', german: 'Dieser Plan ist lueckenlos, es wird keine Probleme geben.' }] },
    { word: '一落千丈', pinyin: 'yī luò qiān zhàng', meaning: 'auf einen Schlag tief fallen; ein rapider Absturz', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '公司业绩一落千丈，面临破产。', pinyin: 'Gōngsī yèjì yī luò qiān zhàng, miànlín pòchǎn.', german: 'Die Unternehmensleistung ist rapide abgestuerzt und es steht vor dem Bankrott.' }] },
    { word: '无可奈何', pinyin: 'wú kě nài hé', meaning: 'hilflos; nichts dagegen machen koennen', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '面对这种情况，我们无可奈何。', pinyin: 'Miànduì zhè zhǒng qíngkuàng, wǒmen wú kě nài hé.', german: 'Angesichts dieser Situation koennen wir nichts machen.' }] },
    { word: '不约而同', pinyin: 'bù yuē ér tóng', meaning: 'ohne Absprache dasselbe tun; wie aus einem Mund', type: 'Chengyu', level: 'HSK5', category: 'Beziehungen', examples: [{ chinese: '他们不约而同地选择了同一家餐厅。', pinyin: 'Tāmen bù yuē ér tóng de xuǎnzé le tóng yī jiā cāntīng.', german: 'Sie waehlten ohne Absprache alle dasselbe Restaurant.' }] },
    { word: '刮目相看', pinyin: 'guā mù xiāng kàn', meaning: 'jemanden mit neuen Augen sehen; seine Meinung ueber jemanden aendern', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '他的进步让所有人刮目相看。', pinyin: 'Tā de jìnbù ràng suǒyǒu rén guā mù xiāng kàn.', german: 'Sein Fortschritt hat alle dazu gebracht, ihn mit neuen Augen zu sehen.' }] },
    { word: '迫不及待', pinyin: 'pò bù jí dài', meaning: 'es kaum erwarten koennen; ungeduldiges Warten', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '孩子们迫不及待地打开了圣诞礼物。', pinyin: 'Háizimen pò bù jí dài de dǎkāi le shèngdàn lǐwù.', german: 'Die Kinder konnten es kaum erwarten, die Weihnachtsgeschenke zu oeffnen.' }] },
    { word: '理所当然', pinyin: 'lǐ suǒ dāng rán', meaning: 'selbstverstaendlich; natuerlich; wie es sein sollte', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '帮助朋友是理所当然的事。', pinyin: 'Bāngzhù péngyou shì lǐ suǒ dāng rán de shì.', german: 'Freunden zu helfen ist eine Selbstverstaendlichkeit.' }] },
    { word: '千方百计', pinyin: 'qiān fāng bǎi jì', meaning: 'alle erdenklichen Mittel und Wege versuchen', type: 'Chengyu', level: 'HSK5', category: 'Arbeit', examples: [{ chinese: '他千方百计地想办法解决这个问题。', pinyin: 'Tā qiān fāng bǎi jì de xiǎng bànfǎ jiějué zhège wèntí.', german: 'Er versuchte mit allen erdenklichen Mitteln, das Problem zu loesen.' }] },
    { word: '津津有味', pinyin: 'jīn jīn yǒu wèi', meaning: 'mit grossem Genuss; mit Appetit und Begeisterung', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '他津津有味地吃着妈妈做的饭菜。', pinyin: 'Tā jīn jīn yǒu wèi de chī zhe māma zuò de fàncài.', german: 'Er isst mit grossem Genuss das Essen, das seine Mutter gekocht hat.' }] },
    { word: '防患于未然', pinyin: 'fáng huàn yú wèi rán', meaning: 'dem Unglueck vorbeugen, bevor es eintritt; Praevention', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '安装烟雾探测器就是防患于未然。', pinyin: 'Ānzhuāng yānwù tàncèqì jiùshì fáng huàn yú wèi rán.', german: 'Rauchmelder zu installieren bedeutet, dem Unglueck vorzubeugen.' }] },
    { word: '莫名其妙', pinyin: 'mò míng qí miào', meaning: 'unerklärlich; seltsam; voellig unverstaendlich', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '他莫名其妙地生气了，我不知道为什么。', pinyin: 'Tā mò míng qí miào de shēngqì le, wǒ bù zhīdào wèishéme.', german: 'Er wurde aus unerklärlichem Grund wuetend, ich weiss nicht warum.' }] },
    { word: '大同小异', pinyin: 'dà tóng xiǎo yì', meaning: 'im Grossen aehnlich, in Kleinigkeiten verschieden; mehr oder weniger gleich', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '这两个方案大同小异，选哪个都行。', pinyin: 'Zhè liǎng gè fāng\'àn dà tóng xiǎo yì, xuǎn nǎge dōu xíng.', german: 'Diese beiden Vorschlaege sind im Grunde gleich, man kann jeden nehmen.' }] },
    { word: '一目了然', pinyin: 'yī mù liǎo rán', meaning: 'auf einen Blick klar; sofort verstaendlich', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '这张图表让数据一目了然。', pinyin: 'Zhè zhāng túbiǎo ràng shùjù yī mù liǎo rán.', german: 'Diese Grafik macht die Daten auf einen Blick verstaendlich.' }] },
    { word: '半信半疑', pinyin: 'bàn xìn bàn yí', meaning: 'halb glauben, halb zweifeln; skeptisch', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '他对这个消息半信半疑。', pinyin: 'Tā duì zhège xiāoxi bàn xìn bàn yí.', german: 'Er war gegenueber dieser Nachricht halb glaeuebig, halb skeptisch.' }] },
    { word: '微不足道', pinyin: 'wēi bù zú dào', meaning: 'unbedeutend; nicht der Rede wert', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '这点帮助微不足道，不用客气。', pinyin: 'Zhè diǎn bāngzhù wēi bù zú dào, bùyòng kèqi.', german: 'Diese kleine Hilfe ist nicht der Rede wert, gern geschehen.' }] },
    { word: '千载难逢', pinyin: 'qiān zǎi nán féng', meaning: 'eine einmalige Gelegenheit; kommt nur alle tausend Jahre vor', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '这是千载难逢的好机会，不能错过。', pinyin: 'Zhè shì qiān zǎi nán féng de hǎo jīhuì, bù néng cuòguò.', german: 'Das ist eine einmalige Gelegenheit, die man nicht verpassen darf.' }] },
    { word: '安居乐业', pinyin: 'ān jū lè yè', meaning: 'in Frieden leben und gluecklich arbeiten; ein zufriedenes Leben fuehren', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '人民安居乐业是社会和谐的基础。', pinyin: 'Rénmín ān jū lè yè shì shèhuì héxié de jīchǔ.', german: 'Dass die Menschen in Frieden leben und gluecklich arbeiten, ist die Grundlage einer harmonischen Gesellschaft.' }] },
    { word: '左右为难', pinyin: 'zuǒ yòu wéi nán', meaning: 'in einer Zwickmuehle stecken; sich nicht entscheiden koennen', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '他左右为难，不知道该怎么选择。', pinyin: 'Tā zuǒ yòu wéi nán, bù zhīdào gāi zěnme xuǎnzé.', german: 'Er steckt in einer Zwickmuehle und weiss nicht, wie er sich entscheiden soll.' }] },
    { word: '众所周知', pinyin: 'zhòng suǒ zhōu zhī', meaning: 'allgemein bekannt; wie jeder weiss', type: 'Chengyu', level: 'HSK5', category: 'Lebensweisheit', examples: [{ chinese: '众所周知，学语言需要时间和耐心。', pinyin: 'Zhòng suǒ zhōu zhī, xué yǔyán xūyào shíjiān hé nàixīn.', german: 'Wie allgemein bekannt ist, braucht Sprachenlernen Zeit und Geduld.' }] },
    { word: '爱不释手', pinyin: 'ài bù shì shǒu', meaning: 'etwas nicht aus der Hand legen wollen; begeistert sein von', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '这本书太好看了，让人爱不释手。', pinyin: 'Zhè běn shū tài hǎokàn le, ràng rén ài bù shì shǒu.', german: 'Dieses Buch ist so toll, man kann es gar nicht aus der Hand legen.' }] },
    { word: '无微不至', pinyin: 'wú wēi bù zhì', meaning: 'bis ins kleinste Detail fuersorglich; aeusserst aufmerksam', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '妈妈对我的照顾无微不至。', pinyin: 'Māma duì wǒ de zhàogù wú wēi bù zhì.', german: 'Mamas Fuersorge fuer mich reicht bis ins kleinste Detail.' }] },
    { word: '适可而止', pinyin: 'shì kě ér zhǐ', meaning: 'wissen, wann man aufhoeren muss; das rechte Mass halten', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '喝酒要适可而止，不要过量。', pinyin: 'Hē jiǔ yào shì kě ér zhǐ, bù yào guòliàng.', german: 'Beim Trinken muss man Mass halten und darf nicht uebertreiben.' }] },
    { word: '捷足先登', pinyin: 'jié zú xiān dēng', meaning: 'wer schnelle Fuesse hat, kommt zuerst an; der Schnellere gewinnt', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '好的职位都被捷足先登的人抢走了。', pinyin: 'Hǎo de zhíwèi dōu bèi jié zú xiān dēng de rén qiǎng zǒu le.', german: 'Die guten Stellen wurden alle von den Schnellsten geschnappt.' }] },
    { word: '眼花缭乱', pinyin: 'yǎn huā liáo luàn', meaning: 'die Augen koennen nicht folgen; ueberwael­tigt von der Auswahl', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '商店里的商品让人眼花缭乱。', pinyin: 'Shāngdiàn lǐ de shāngpǐn ràng rén yǎn huā liáo luàn.', german: 'Die Waren im Laden sind so zahlreich, dass man gar nicht weiss, wohin man zuerst schauen soll.' }] },
    { word: '画龙点睛', pinyin: 'huà lóng diǎn jīng', meaning: 'dem Drachen die Augen malen; den letzten entscheidenden Schliff geben', type: 'Chengyu', level: 'HSK5', category: 'Erfolg', examples: [{ chinese: '最后的那句总结起到了画龙点睛的作用。', pinyin: 'Zuìhòu de nà jù zǒngjié qǐdào le huà lóng diǎn jīng de zuòyòng.', german: 'Die abschliessende Zusammenfassung gab dem Ganzen den letzten entscheidenden Schliff.' }] },
    { word: '息息相关', pinyin: 'xī xī xiāng guān', meaning: 'eng miteinander verbunden; untrennbar zusammenhaengend', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '环境保护和我们的健康息息相关。', pinyin: 'Huánjìng bǎohù hé wǒmen de jiànkāng xī xī xiāng guān.', german: 'Umweltschutz haengt eng mit unserer Gesundheit zusammen.' }] },
    { word: '名副其实', pinyin: 'míng fù qí shí', meaning: 'der Name entspricht der Wirklichkeit; zu Recht so genannt', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '他是一位名副其实的专家。', pinyin: 'Tā shì yī wèi míng fù qí shí de zhuānjiā.', german: 'Er ist ein Experte, der diesen Titel zu Recht traegt.' }] },
    { word: '丰富多彩', pinyin: 'fēng fù duō cǎi', meaning: 'reichhaltig und vielfaeltig; bunt und abwechslungsreich', type: 'Chengyu', level: 'HSK5', category: 'Natur', examples: [{ chinese: '大学生活丰富多彩。', pinyin: 'Dàxué shēnghuó fēng fù duō cǎi.', german: 'Das Universitaetsleben ist bunt und abwechslungsreich.' }] },
    { word: '心甘情愿', pinyin: 'xīn gān qíng yuàn', meaning: 'aus freien Stuecken; von Herzen bereit', type: 'Chengyu', level: 'HSK5', category: 'Gefühle', examples: [{ chinese: '她心甘情愿地为家庭付出一切。', pinyin: 'Tā xīn gān qíng yuàn de wèi jiātíng fùchū yīqiè.', german: 'Sie opfert aus freien Stuecken alles fuer ihre Familie.' }] },
    { word: '自力更生', pinyin: 'zì lì gēng shēng', meaning: 'auf eigene Kraft bauen; sich selbst helfen', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他从小就学会了自力更生。', pinyin: 'Tā cóng xiǎo jiù xuéhuì le zì lì gēng shēng.', german: 'Schon als Kind hat er gelernt, auf eigenen Beinen zu stehen.' }] },
    { word: '若无其事', pinyin: 'ruò wú qí shì', meaning: 'so tun, als waere nichts geschehen; betont gleichgueltig', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '出了这么大的事，他居然若无其事。', pinyin: 'Chū le zhème dà de shì, tā jūrán ruò wú qí shì.', german: 'Es ist etwas so Grosses passiert und er tut so, als waere nichts gewesen.' }] },
    { word: '寸步不离', pinyin: 'cùn bù bù lí', meaning: 'keinen Schritt von der Seite weichen; staendig begleiten', type: 'Chengyu', level: 'HSK6', category: 'Beziehungen', examples: [{ chinese: '她寸步不离地照顾生病的丈夫。', pinyin: 'Tā cùn bù bù lí de zhàogù shēngbìng de zhàngfu.', german: 'Sie wich keinen Schritt von der Seite ihres kranken Mannes.' }] },
    { word: '一针见血', pinyin: 'yī zhēn jiàn xiě', meaning: 'mit einer Nadel Blut treffen; den Nagel auf den Kopf treffen', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '他的评论一针见血，说到了问题的关键。', pinyin: 'Tā de pínglùn yī zhēn jiàn xiě, shuōdào le wèntí de guānjiàn.', german: 'Sein Kommentar traf den Nagel auf den Kopf und benannte das Kernproblem.' }] },
    { word: '不择手段', pinyin: 'bù zé shǒu duàn', meaning: 'vor keinem Mittel zurueckschrecken; skrupellos', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '为了赚钱，他不择手段。', pinyin: 'Wèile zhuànqián, tā bù zé shǒu duàn.', german: 'Um Geld zu verdienen, schreckt er vor keinem Mittel zurueck.' }] },
    { word: '日新月异', pinyin: 'rì xīn yuè yì', meaning: 'sich tagtaeglich veraendern; rasante Entwicklung', type: 'Chengyu', level: 'HSK6', category: 'Natur', examples: [{ chinese: '科技发展日新月异，变化非常快。', pinyin: 'Kējì fāzhǎn rì xīn yuè yì, biànhuà fēicháng kuài.', german: 'Die technologische Entwicklung ist rasant, die Veraenderungen sind enorm schnell.' }] },
    { word: '南辕北辙', pinyin: 'nán yuán běi zhé', meaning: 'nach Sueden fahren wollen, aber nach Norden lenken; das Gegenteil dessen tun, was man erreichen will', type: 'Chengyu', level: 'HSK6', category: 'Warnung', examples: [{ chinese: '你的方法和目标南辕北辙，需要重新考虑。', pinyin: 'Nǐ de fāngfǎ hé mùbiāo nán yuán běi zhé, xūyào chóngxīn kǎolǜ.', german: 'Deine Methode und dein Ziel gehen in entgegengesetzte Richtungen, du musst das ueberdenken.' }] },
    { word: '感同身受', pinyin: 'gǎn tóng shēn shòu', meaning: 'mitfuehlen; nachempfinden koennen; Empathie zeigen', type: 'Chengyu', level: 'HSK6', category: 'Gefühle', examples: [{ chinese: '你的遭遇我感同身受。', pinyin: 'Nǐ de zāoyù wǒ gǎn tóng shēn shòu.', german: 'Ich kann dein Schicksal nachempfinden.' }] },
    { word: '匠心独运', pinyin: 'jiàng xīn dú yùn', meaning: 'mit meisterhafter Kreativitaet; einzigartiges handwerkliches Geschick', type: 'Chengyu', level: 'HSK6', category: 'Arbeit', examples: [{ chinese: '这座建筑匠心独运，设计非常巧妙。', pinyin: 'Zhè zuò jiànzhù jiàng xīn dú yùn, shèjì fēicháng qiǎomiào.', german: 'Dieses Gebaeude zeigt meisterhaftes Geschick, das Design ist aeusserst raffiniert.' }] },
    { word: '当机立断', pinyin: 'dāng jī lì duàn', meaning: 'sofort eine Entscheidung treffen; entschlossen handeln', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '紧急情况下他当机立断，避免了更大的损失。', pinyin: 'Jǐnjí qíngkuàng xià tā dāng jī lì duàn, bìmiǎn le gèng dà de sǔnshī.', german: 'In der Notsituation traf er sofort eine Entscheidung und verhinderte groesseren Schaden.' }] },
    { word: '一蹴而就', pinyin: 'yī cù ér jiù', meaning: 'mit einem einzigen Schritt erreichen; auf Anhieb gelingen (oft verneint)', type: 'Chengyu', level: 'HSK6', category: 'Erfolg', examples: [{ chinese: '学好一门语言不可能一蹴而就。', pinyin: 'Xué hǎo yī mén yǔyán bù kěnéng yī cù ér jiù.', german: 'Eine Sprache gut zu lernen gelingt nicht auf Anhieb.' }] },
    { word: '开门见山', pinyin: 'kāi mén jiàn shān', meaning: 'die Tuer oeffnen und den Berg sehen; direkt zur Sache kommen', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '我就开门见山地说吧，我不同意你的方案。', pinyin: 'Wǒ jiù kāi mén jiàn shān de shuō ba, wǒ bù tóngyì nǐ de fāng\'àn.', german: 'Ich komme direkt zur Sache: Ich bin mit deinem Vorschlag nicht einverstanden.' }] },
    { word: '卧虎藏龙', pinyin: 'wò hǔ cáng lóng', meaning: 'verborgener Tiger, versteckter Drache; verborgene Talente', type: 'Chengyu', level: 'HSK6', category: 'Charakter', examples: [{ chinese: '这个小公司卧虎藏龙，有很多优秀的人才。', pinyin: 'Zhège xiǎo gōngsī wò hǔ cáng lóng, yǒu hěn duō yōuxiù de réncái.', german: 'In diesem kleinen Unternehmen verbergen sich viele herausragende Talente.' }] },
    { word: '声东击西', pinyin: 'shēng dōng jī xī', meaning: 'im Osten laermen und im Westen angreifen; Ablenkungsmanoever', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '他用声东击西的策略赢了比赛。', pinyin: 'Tā yòng shēng dōng jī xī de cèlüè yíng le bǐsài.', german: 'Er gewann das Spiel mit einem Ablenkungsmanoever.' }] },
    { word: '独一无二', pinyin: 'dú yī wú èr', meaning: 'einzigartig; es gibt kein zweites', type: 'Chengyu', level: 'HSK5', category: 'Charakter', examples: [{ chinese: '每个人都是独一无二的。', pinyin: 'Měi gè rén dōu shì dú yī wú èr de.', german: 'Jeder Mensch ist einzigartig.' }] },
    { word: '一波三折', pinyin: 'yī bō sān zhé', meaning: 'eine Welle mit drei Wendungen; Komplikationen und Rueckschlaege', type: 'Chengyu', level: 'HSK6', category: 'Lebensweisheit', examples: [{ chinese: '这个项目一波三折，但最终完成了。', pinyin: 'Zhège xiàngmù yī bō sān zhé, dàn zuìzhōng wánchéng le.', german: 'Das Projekt hatte viele Rueckschlaege, wurde aber schliesslich abgeschlossen.' }] },
    { word: '万事俱备只欠东风', pinyin: 'wàn shì jù bèi zhǐ qiàn dōng fēng', meaning: 'alles ist bereit, es fehlt nur noch der Ostwind; es fehlt nur noch eine Kleinigkeit', type: 'Chengyu', level: 'HSK6', category: 'Geschichte', examples: [{ chinese: '我们万事俱备只欠东风，就等投资人的批准了。', pinyin: 'Wǒmen wàn shì jù bèi zhǐ qiàn dōng fēng, jiù děng tóuzī rén de pīzhǔn le.', german: 'Alles ist vorbereitet, es fehlt nur noch die Genehmigung des Investors.' }] }
  ];

  // Register chengyu data globally
  if (!window.CHENGYU_DATA) window.CHENGYU_DATA = [];
  window.CHENGYU_DATA = window.CHENGYU_DATA.concat(chengyu);
})();
