// Writes scripts/hanzi/STATUS.md: hanzi enrichment progress per level.
const fs = require('fs');
const path = require('path');
const enrich = require('../enrich/common.cjs');
const hanzi = require('./common.cjs');

const rows = {};
for (const entry of hanzi.loadHanzi()) {
  const row = rows[entry.level] = rows[entry.level] || { total: 0, reviewed: 0, withReviewer: 0, writing: 0 };
  row.total++;
  if (entry.writingLevel) row.writing++;
  if (entry.review) row.reviewed++;
  if (entry.review && entry.review.policy === 'author+review') row.withReviewer++;
}
const order = hanzi.LEVELS.filter(level => rows[level]);
const total = order.reduce((n, l) => n + rows[l].total, 0);
const done = order.reduce((n, l) => n + rows[l].reviewed, 0);
const ledger = enrich.readJson(path.join(__dirname, 'ledger.json'), {});
const md = [
  '# Hanzi enrichment status',
  '',
  'Generated by `scripts/hanzi/status.cjs`. ' + done + ' of ' + total + ' characters enriched (' + (100 * done / total).toFixed(1) + ' %), ' +
    new Set(Object.values(ledger).map(e => e.batch)).size + ' batches applied.',
  '',
  '| Level | Characters | Handwriting | Enriched | with 2nd reviewer |',
  '|---|---|---|---|---|',
  ...order.map(l => '| ' + l + ' | ' + rows[l].total + ' | ' + rows[l].writing + ' | ' + rows[l].reviewed + ' | ' + rows[l].withReviewer + ' |'),
  ''
].join('\n');
fs.writeFileSync(path.join(__dirname, 'STATUS.md'), md);
console.log(md);
