// Writes scripts/enrich/STATUS.md: enrichment progress per level.
const fs = require('fs');
const path = require('path');
const common = require('./common.cjs');

const sources = common.loadSources();
const rows = {};
for (const source of sources) {
  for (const item of source.items) {
    const level = item.level;
    rows[level] = rows[level] || { total: 0, reviewed: 0, drafts: 0, withReviewer: 0 };
    rows[level].total++;
    if (item.review) rows[level].reviewed++;
    if (item.review && item.review.policy === 'author+review') rows[level].withReviewer++;
    if (item.meaningStatus === 'draft') rows[level].drafts++;
  }
}
const order = Object.keys(rows).sort((a, b) => (common.LEVEL_RANK[a] || 9) - (common.LEVEL_RANK[b] || 9));
const total = order.reduce((n, l) => n + rows[l].total, 0);
const done = order.reduce((n, l) => n + rows[l].reviewed, 0);
const ledger = common.readJson(common.LEDGER, {});
const batches = new Set(Object.values(ledger).map(e => e.batch));
const md = [
  '# Enrichment status',
  '',
  'Generated by `scripts/enrich/status.cjs`. ' + done + ' of ' + total + ' entries enriched (' + (100 * done / total).toFixed(1) + ' %), ' + batches.size + ' batches applied.',
  '',
  '| Level | Entries | Enriched | with 2nd reviewer | Draft meanings left |',
  '|---|---|---|---|---|',
  ...order.map(l => '| ' + l + ' | ' + rows[l].total + ' | ' + rows[l].reviewed + ' | ' + rows[l].withReviewer + ' | ' + rows[l].drafts + ' |'),
  ''
].join('\n');
fs.writeFileSync(path.join(__dirname, 'STATUS.md'), md);
console.log(md);
